[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8ded18b3d7656cf5d1237dbdf92d3874acf6282a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f5e26aa6e7f40a189d58a22296cc1a32e72ff9213265490a1a858baa95c5c019"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "b83a5f05089c45f31f1df86c538687c5e37dd7ea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "96dfb268bfc4686ba8810f0f41e46ac42fe164d20354f4c4b31256bdf1a5766a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "7a783d03c48828ff970fa7c8d37506d9a6240c7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f88fd834673ac8881dcc2d1206880d4ae61cc23f121b55802c508052037e7f59"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "586aa585c8ae9573c3ddbc034a5553142556184a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f1b4313e82113ad1fc06144c80f44ecde8a14cdfa140e9f7ef6925364e3ac075"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "08db34a399e31161750926db32814f3dd5235adf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "998e80973ff85048ca05b614f0acf4cf8ccc2aefbfde00285f33be830b09fb6b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1b5a108f1a2cf259c1c70619fd3c735940c4ba04"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "662a51ea72d214fefee8109fd4a6f1ce9f093a14a5550f0a1c64f0e85affdba2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "e2b86f181a13fd963a93032a540e8c662637b85f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e26330f2240d666f8c75575ec22bc68140326f1cf4417538217965f395d653d4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "77a133bc4d6b7ea2c4e920deea3002ee718f8c03"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "ef4c99d359196be5602db6fd008298f4b0ff48abfd1d9956cd5eb197284d8949"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "09a9a66d07aaf215df6f892266e64962f366401a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c31933623e20e65a65ea3937832d85725d815cb0518645ceaf56a5bc406f093e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "38dd680caf1d96803fdfb1c3d994267e9f3e016b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7868a89970533cfb4ef8ed9991405fc1c342c3012e3c79f5ed2ffccd04e6421d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "a2b0a845b2d9e8f8d63de085c7949d3e5986b093"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8df09b414916c6418a73f1e3f9a404fc4354169fd29d4790ce7be7763ceba54d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "64630346c0a317569321aa4f0303018dade237a7"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "9fd3e0cae8123ba6325365837c1dbd2281b24ca53de6e42b822818a364ae04f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "99e1a7e59d9084238667e444fe942539dedc31ab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "969d429edc14ebaafca9c73c429507eac272eb3b3f88804c42d487d3a451065d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2d62312ee0b46a40fe01080f8a65eb6e08c90a77"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9f5722f37477261c38c1714146e14d085b6bd23b2e079ea72b8df0fb99f5ca87"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "fd9fdaec5d296e227770185f056105b7e69fad8c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "239345b09229d893973544264341b3367f8fa5dfea19d8b401c2608254bd3972"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "636fc9416b46e81fb80cd092c26c6098a5ceab87"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3c5d6208a23415a3333c818ddc6c082ac93562824be144e49877a10d5ecb7219"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8fbb48d6717fc72bcba5b365843e7b033756bb46"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bf39434b519940d9c1e8b3c1f1e32994813f46ef382c3d69b098419992c81465"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "0284a06bed0083c601059d81a607000da1e7e1e4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7d7ea64f665a2ebcd13d5f64a91afa63f7afaf4e205ef9297336dbcc30cf6dab"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "e5851a6d8aac589ffe3cca0a5a3c9e6c4b0724f5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fb47dcee70919ccb02764af0910e8d2717bf72438927df70008ef68e64b6c286"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "998e726a5abddbe98e8a01765e3aff8f88ea123a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "bbc684cea35f293ffcd25ba0fa6d496b44a458fc1bf6e64f902786df3986f139"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f930a712a72cf60b07cfb2afe99596f2c45fa93b"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f5654445928a2d5c718c4e107253ea5edebc7a43fa6f25303023d88147bdff3c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "53907f96ee4c276035aa5098e78012c92aed892c"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "34432e4b1945ca8750d388f4bb34d4a6435f4e2dfc49f053ccfb0b074605a230"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6d5b31544d0080d0a9d9b7dcd870ed114f9f2608"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "71179403007ceecc74c45906343d0f3bf701a87cae5b171ffbe348124beda986"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "bd0f52e86610dfdf4c846a945d56d71a82922990"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7ffbdc94c8066f41ee1701bdef99e8358a09d255c5e8a2ae2920cc0bedd91315"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "c6b6f0acb062bc4d65610adf0540e13d18f97cdb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "50194e01444efcf96b772a9cfed4cadd0c75997ac22a539454b4968f05192dc0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "74136b3d5b812a0b7da9a9b186f857f1a622dc7d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e94621538b7ac66d0acac28880ef09df375bb7f35bb779e2d69bcb2bf393fc19"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "cfb0852e3f081e01f4575c52259fc8b2f3988615"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "2fc6a62b67880ffc6b2bcb8c952496e30d4c8a57aefec4814ec58d9cc26fdaa3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "06d406828d3a8704be88eab632b44a5063d4edc3"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "184aba20fd8641214b627b00d440fb4d23dceb7b722180621b00a17568dbed35"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "3e164c19f5999f1a6eaea38f56186f9f9dea05c3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "35833ed020ad07e04674c94178cec09a408729126c7e7ae7dc02978f51e7256a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "af7482b4e7c9937de685fd06d41b168aeb7b2299"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "861e2f4bb5e8d8b6a28545b1f49031e31cbcdc93ce87db745b23d3d91df68b24"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "95eedfba1c80016a0a430ac981a227a4dc44555b"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "54a047e587dda234a3de39d3f1b8b2e89d967fbb9e61580093f71eb31f38ea08"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "241fd2cf0e8d3faa733522ec7e2fa29f6c3f5876"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b7df1732c95d3a498d4f0e16cdac64af21e29695fe3cdf8a49d2ee1d5a173182"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "74d2ffcb84ec018a7eb662eff2ec45c19a61b15c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5005fa99f2e74dd139d0495f42adc3d71198a4382c28f92941168f2add98b1cf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c2d4a2da24ff7b6a8dabfec84c1e08186eccc532"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46db6b09bcb59d098597df396106504b46f92685b3fde097ada2646446c644d5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "74ce338b134a6ca86a1149e4474bd78f709238d6"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cf548492ca9fbbb1dfec912e5c9afef0952cd6a7cff84f8a25a3ce3583da1f16"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "fb0c33e9e98882fc31f8dbf35aebbf5e97c60683"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2c2256fe26cf39f6af09b9639482c96e462359f0b44f7bffdd572bc0816e0164"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "142b5de052a560c6c398a0d4f354bd130f6b47a4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f3c4ef0944d9decf3c769746077776f4c44c81be28a4cb82fbd3df954fca5062"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "9c2c32a24eb6366dcbec4a86acd41095d464e2e7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b4f815751a0ce9f4e6818696a67c660ece8ff847e8aa2d8474057e9db38f74a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0ef906be043124d5255f44f7d0245acc6c425ef6"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "f4b6bf9cbbc7e5ddb578505734d7a48dd5c107c52ba087a22e813bdc61cd6dcf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+0/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran3.tar.gz"
