[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "ae96f5d2e64403fa9c99e372120b5749bf6f123b"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "3f2cef9b4a12e80960dc9cdfe6527da4d91f0ef4f9e11127c1ba3bc80b3c0ace"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e2b483d55a850bff6acc9338983662a96471cc4c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c81425eaa8b6adda4ad54c881be13abb362809237bc0c2bf427ca5641a1ffda1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "0584d4cb21538c1340aa190f9569bd18e795fc03"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c06a123eae1f1b66f30b3bbd0ff0385b3858d5ccc2f2b7b4d742d1e91d6583e0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "239f69eb997224ac6c6432c2f2152e7173bee634"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ea98e21fb213700c3994704805e17fcf9249369c5b897da94f1d949712852236"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "aff6da444a1f2717a0641740abe060ae4e74ba04"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fa5b03cf7e38b41d585f87754f4d0d0f731a71f30ce7445e4396752c302cf7ce"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "b9a56d89e4215fae8ce3e3f2f917bc9c883e4d86"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46aacc88b8d4b9b1cdd91da958ef5591e1abc58ce157999df9d222f4e2f9d35e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "7c8ea89b01dab4906221295f7ada8d3af372747b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "812765d3dfe46acf4903a84abdfb4e0b4c41d9a6b0a30ea41b35db64bfb949c9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "effc15a9d38f290a4d6b00400afb884a08887196"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5728a6b6fb2a4f5e653a90fdd822f769a5747d989fba16a1b8994942c335c3ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4deb2c1706b360c48f985306a13c02d03716494c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7235369f4ec275b2e51734ae917996a3dbeac8f1e5d2c2a27cb266261712a270"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a5fa28e7d5d40356f37c3452094ae1153fb9614"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "81027dcf4862022f615a0832297689d31883ac236adc1582581df06867e1a5a3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5caf7366944e07ab917bc97706d825329070ceb6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c23db2ec8a8e949a1f2afa01e60c173086db734646e83f5f25103dae0bd2bcf9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6a85e6becde55d20c383902dba05ff392a4e1975"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3085cb597524e332004a7eb95c13cdca7a6f5e535ace2eb86e3ce00362fa45d9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ff9f46afd7215190b50250cc0a807df971bd0c0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ec15f04706658bbfe627da5e42f57c8c5c6ca85dc94cc65a1cb846dd1c0f40d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "effc15a9d38f290a4d6b00400afb884a08887196"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5728a6b6fb2a4f5e653a90fdd822f769a5747d989fba16a1b8994942c335c3ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4deb2c1706b360c48f985306a13c02d03716494c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7235369f4ec275b2e51734ae917996a3dbeac8f1e5d2c2a27cb266261712a270"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a5fa28e7d5d40356f37c3452094ae1153fb9614"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "81027dcf4862022f615a0832297689d31883ac236adc1582581df06867e1a5a3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5caf7366944e07ab917bc97706d825329070ceb6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c23db2ec8a8e949a1f2afa01e60c173086db734646e83f5f25103dae0bd2bcf9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a85e6becde55d20c383902dba05ff392a4e1975"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3085cb597524e332004a7eb95c13cdca7a6f5e535ace2eb86e3ce00362fa45d9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ff9f46afd7215190b50250cc0a807df971bd0c0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ec15f04706658bbfe627da5e42f57c8c5c6ca85dc94cc65a1cb846dd1c0f40d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "4dfbed400bd760e86706ec95dcee9bcdb8f98d17"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7a010a208c237d18f6533b937deaf36df220fa26156289c58db54de06aafb521"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f6ee44f45ed4deb299aaaec2f5a5770751fc5744"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c72fecd1a2fef7b80ef899d976635be5a0767b62b2858dd50a79bc91313a34af"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "84dbe984e45f7ce9bdd491263fa64ecd268f468f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c8a2edd0f4a5a92a26fa5f424154a41a4e5d79a22cb68e07c60add5db59d4a6e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "583484ae400ba46d8e9f662d30be761ac9f02e7c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3086f3ea1059c2eaaa827b03b2ec69c056b525e1381f245dcaa3cbc53a4fab4a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "e1156004dd13e1684c506f14b2cdad212303d104"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "acd7e185cc42ea62b237cefd587f5a33ce81e4452ce7678f619efa765da7fc1c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "69d87c49b661a4a3541ee9bcb7fea50684903dcb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "05ebb437aeb1e5e3b1e2e7fa47e23252e6c76c67cd732695453ae63b41b16d43"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "90c599fea78c56e551cbc3f7cf0458d27760fc68"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "ef673975f9c62e1ed341df0809a50d38a3efa195b0ad9fe99166034618dd4c11"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "feb2534f61b39d742bdf4e70646a7b8ef1e31e1e"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "d1c20671ec17ffc9dd377d1e3be1bf6d673d56f8019c80b08b36a20d81947835"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "11c3f9de4a50c29d85b00c300f48157088e8c58b"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "fefaa45be87e7db6038edb83315cb6033ce9c002216d66e2c006c6de5b7e3b74"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "f4b6d3dd3602d765ae9792228d7ccfa96edae36c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "88f974839fff34a91121e3142961f99349d90582acd5a474b9f58cded04227be"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "c0b3d97b506a96062eb68090f187e01add3bc7e2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4cd2f69045b106b78ff5089f9f5ee34e77e893f3f5c64e63cd5d46a4a4f9abe8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "2fb257ede06f00268b7dfc3a749b328383c30d77"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "548715ff2a7d5fda92fa0880b623d9ff68f6a470c3a6473b04095898a06b96d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2b3b7aedba814d46754cd313875532d68934a059"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "ff1fffb1c8e00edbd72d043e39d182f14a2221b5d6bbfa2affc3cefd73b15345"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "4b62595c5337c547ff1b67351ffa6bcc7873a3f6"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "8b57711184323cd43e368544ac5139c4210c6c2ed549fa64ba5af4f3157b10d2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0e5cb58d59ec4dffa6adeb635192863c1dc6f031"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "61d7f0dd53f4101d23a86a3a65902ca48cf63512602e15727b98033d41c49b32"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2ecc967ed84620999e98e1a55bf6d8269c8c2ba3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bee24a94fda8abace4c4077e726e258121b580016befeb7bae420c98d7c23e8c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "afa6c359f18c5ba7504e5b96f13245233fa61570"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7df78a336b41ecec5b4781e91078a4fe47e4c7192b52d7952fc41d4e5f3878bc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ccc6f8777195e7d6b2847936c6d3f49cfeb0ac2e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ab5103f4fdc006f209313e97cf398c451092d7ec2718a3b36326822d3cfef853"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "05449dd2069d4b8e4f47c6dac3eb513b4b091e8e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3b2a76e879b7c14a750ce96bea41a7e619e6302ce2772742acef26027d1cbba6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ddd32ef2b522e46c1fde251282e8e9f4d10de504"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "227e60aba94ea09357b1f18a950100bbd37d231fe3e8eae74b178d14cbc64185"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f18b7a49e0a23314a288806d5e6faa3086a6557f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "17588c2ee101c6a2270568702b778e2a9ceeeec865c98e04974ee4270116abea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "db5801a818780056c33fec9297453e3e8e42d6bf"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "8341668c5911b2ec406ceee9773c6d35bbb73b7f8d81d074dde85d8ee62daad4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "17ad3a07e57626c14764a5442d62e7538a77d23b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "eda64157babdbbd140784fe6fa62bdfa9aa8db99c196707f35eb1d5f75370142"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7c9ff37e2ae17235b3da8589e50c0af4440da3b0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "73c4dbe3df4a0d65cc7e3373594e44eff9d5a544c67b6b84108de461d543df79"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f6c6c06df8ba68118544d1ecd2ea00fc0e007bc1"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "5732d2d5f217e0e9cd0f76ff9fcb326278cad88b9eed9faaa08aae1f58cbbb44"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e3227854ad57784606f18c65a06bf37ddcfbb727"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "5346af2326a63fbb96f3902a9491a2cb47ec7fc8301c38d04be6f81cdc33a920"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6a5b0dd4581dfdfc45ff8b15f691d9a12d590cdf"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "9121f50564a01ded5d108f204cd400eb315e5018401c8a1f42df2f0a7e12504a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.25+0/OpenBLAS32.v0.3.25.x86_64-w64-mingw32-libgfortran5.tar.gz"
