[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "7ab691b2ce107194cd3a5c45bbefbd8d4be67b12"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "1bbc7562eab36ba737cc11529425b209654d36e6710e00f6affae98d6c8bb0bc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e6760f183ff4864340bcc9a783ede6d76e0d336e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c51143d65772d4e2a9f5229ee59d849eef85daaed57ce0a83e3d3e47338db6be"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "6a2d92db29b7e6a05a9d61ae7a7881336b3a243b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2f992f627892ac0f9d45b144e1b23e65d01a9fbd700a41d4d0098587e4aff458"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "406adb9aef4d5a89c1b0247c1b11b419ab5f0883"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0908ce6f89b8fc74dd6e2b5c6cb0de38476f211065d2c93a1cd5b4b38088e40d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "b1b09528555e569cc4104ab03969a1ddec3f1cf7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "36b53a9f10e1484dd9c27175774c25856c5a78b0f6c591ed1a743616e0ec532a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "7cf96b89e96ec0e1edfc6e3b87fdc77d31c3b28c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "56afa25ba0876dadfc5dc7e8a5eecf68a021888775e3d863d65a7851e93b0e75"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e3a622996b1b3d01b05f4becb3766f8a9716d326"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "aa38e0eba3b3ff2d0e72e4abb40aacf75e7373ba8d960fd0d5f90f994ae5411a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fdba4e9b519ef51be02b1c279c75c5aff7dca7a1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "331fd194eb52d936d44508814f9731e6322c0c68d94cf1c48356d69ea539a451"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "55c022c7fd0c5657abd1a1fa170c6c1c51689878"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "00711847fa049bda1c092cfa15cfa4e325cf59558896c182f1432a0949643856"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53ad3a588f4c9fe39d95127d155a00f76f186679"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0251228c2168d1077dbbf54230ba36f6cbc155eb1e51a0ff9b82667b339fe5aa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "44897670b0e1ef3d17f532f3e60937fef0951ab9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "400239a651c5ebfbff0a43b63eb98e81b490a4502a9980c803757e6f2d90a33a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "560a29073ad316ae7476e71b339be904359c74e3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9c9df7cf5cba48c6925406fcbd0036a4f06897e1a63ef576f48bc28555977a5c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7d63cea8481e05fff49542cd0beb0522b025132e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c1f0771c3ce114cf73d88fd3bef27dc992cc6f4633a64c71e80e6f470c3cea66"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b61547391b0f6230996572f5b7bce9a25d6bd639"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46c7f0449005561ad6f0fc0c918deac9c9c5dec106c2d3309619ac6578673f1d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61f46be9713de16070edcc66e4f3843adc7a118c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1d2339ebe1d5b64271fa01998e6fe4956039d0d3cbafe82c87501d9aeef65233"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "657ed5091ede969a5317a79cf2c42981f8705673"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "94171d53dc6a6719ccf92f8ea70975d3d3d161e4d4779c9fcb0b575b42c27792"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9033539bef1e746be7079bde5f1d171f125e08e1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "28783d14875acf4e5299f7c4de4be2d4ba745566779fccc7eb7f387296a3ec68"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a0707c15a9f6bda3970c727d713812c54800ca1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6e2f391c7e0890d247b423931d33f02eaed18e4dcd3588a0c9705f4fb1dd4d59"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94ed4144ea146a907154c3b5d935b3c59bb35546"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "02ea7760fe70fb74b15e312c84361806d03f686f5796907a1f687711f7bac74d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2a7a6c7a8345635dd42cddf8fca8b28888ef9cbe"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ed0e0af80fdc95859766b3c1718e2fa5c0def8f3303fcb9440e653d829fbb58e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "710f0ea7408c2bfa31bc16631df2bf9f34c4c3f1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "aa0e2c3964f42b4ec3c5b43de04ec9100b6d14e6338e840047ba2a6239a1d4af"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "270d10dc2b4404a1a6c291452f14db27b16733e6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3b0ff84ea73b2afb574b7e9f93891b7d36520891d419bbac3ff259e7a4fe87f6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b76442e8ef79507b3310eda41afee2b4e3d6f9bb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "893c8bbf39fe17bcc977b655004dc12f42240041336690108d90e838140b8071"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "335114327cedb83a79dd0f65ec96f4d6cfcecd48"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8445e0d9f55dbb9ab0c3405aa6051ee573e5e2daaec0f7335e5e016c2932e073"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d3546e5ee6387ffc8cf4b86f5d8801f48beb25b8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a27ef25e3c9875912c25d80df9f8628fb6b1ba59dc05e7a3b0cdff4871471c71"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d1ed9ccea37b1483d149e14b575817f578aacd62"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "0675aec959e195e63753ae8c867a266a8d1ee0cfb930c5c612371637b78e4e60"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "93a1634dbac306ac3c8bd2022d1de90aed81c378"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "76ec7239705ab1992f341009c3ed6391d737b1069f413aa3eafb1d10bdc30c9b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "37b14c18694f99ee10821a83703c657b7d491ccc"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "65013dec10463cbc4a761c05fd3494982be7cd1208798fd6430683e7735f2a3e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "8587da9cfabd26a4f2f43c1de8e0b3a37fdad46c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e5840c28de349093f449f1d172fe3cb00d79047f616e0ee9c8f5961b8c25d312"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "5babccdbabc957604041e7ab24fabcbf0a80fc41"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "55d7c1d5aca8252b5e99b56001bdab000a6a95694c67c20499800516218f7f8f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "4991f497bd2746283c7446187da3c8f4d7590ef9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "32c50742e0d06b9aaa07abc065c0028d66e8a112edc42a3f700b9732f02384d2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7b800c56a6758400d58bdd7c8d92bdd9cd7930dc"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "20a711c487dfed549e99dd5599fc74aa5c810418860d91d53ea4465291d2c064"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c82d0982c35ecd0288d4804a379102c2ac21cae0"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "e0e6da3afb5bd4fe72e85204c519970180a4a65d9e7380ca100fab02a13f53c6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "4311e228331d3ce92977090828b0bccd2d9a338f"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "1d4de1bd41e5d3e06b38c45bf7e447b0143714bc632223c74d20179ba5ec2c1a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "bc3d95e745112b6a83d90d5e8fe8c39e0f53a35b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2e1ec2512e1d1a1ca4bd5fb1e5025adb383eb79f5c19e6a644ef94bf65b6aaaa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ea1be0c7ae1ea20bfce1fd54c28a28881a96fcf2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ce1a828c28cc4ef3ed44635b62cec16b20ec5a9820c1a7a60042e6258943b44f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f74bd36b5ef9bd99765bfce9e24a737b7a8134d8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "31b1b24431e05d8516764130fd10e1f57996b04306403182afe1da24507f8a8d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1f798008242b13fb1ffe9106f8c3dee7f346a292"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "79009e5cb6bb93f0f3b9918f39ddd1e886f99574bb2be36d759d6dce52535998"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "909f97847e0dec5e1eeda086ac6a5424caee0336"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cec0a8cac5ecf520df21faad31a789de5836e237798e959a91d139a371445d30"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "396d4ea1c6859f3e49285ffa29db11d05b2943b3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6839eda59676ce0c5d52d7e20eaa65ab3b4fe2c7978f999eb069a2d160f5d3e5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d42d74e1540486055ec038b87f2ec26fdf12b550"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "130090da55d5a8b303c860a9312756211656f7ec2137942439e4be0f497e9af2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "64a8c3e3d8a3768db8151a6c6a2ce9346ed0c493"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "9288700713cac810ad121177d8642c8e2cb54411f845204d140bfcdfe7991a22"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "4e5135df510965c2989088aa517e9d0915f83466"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "8b9519f12130e2ce142302035b894720f75910a3fb4be366b6bb8bf1942cc65b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0073abf4e3ef56c26dc993c7d246202972d6de28"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "921d8dbf178d43b69767cf3ac6b0bfd53f5f44aafc2863768d236eb75257ed9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ee371e82cdabbf2d0f077e90fe6058ceedaac9a2"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "78544b608daf48f6ec359eccc09f69dc784953ffe5b18b24c0038a1841a054f1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "545b9c56775fc1060b175dcce151a2776b199363"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "ec3ec6f44a0c1050e4f8b30794e63941f49a02379905c7e499930f9987dbe74c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.10+3/OpenBLAS32.v0.3.10.x86_64-w64-mingw32-libgfortran5.tar.gz"
