[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "70df967de4c217f30d7e7118efae910c74e5857c"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "efd09de918d4c1361004ad20e78df79dcdd7b736e1220a79ff724fe2bf8bf4c6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "b7a3a17cf7e7af2ef7a4d93df31e1131c4c1f02b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4d28a7128c42cf4d25d0873fddce599f119a2536f6e8b1023df3d4cd6fac6cc5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "3447be4367f9e1d07581134c1df7de4399afa3ff"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bf6a3f65d8f23b05b8dd0bbbc00b26ecbc7a1ac013fb5f74f94bb9895538ac03"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9bcedca56abae7ba2c32c7e1786f2ba057de3f69"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7e2984c19c7131562ea6b434cafcd8a836b4a49d548f57265397cb990bd2e868"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "f6ad03f2e90c2334b016f74b59e92c28d7683ecb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d0bba46cedf146f08ec482c3fdb5409ead7f92e5849010354d23aeed11002164"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "340a32c11764ed40695decdbfdd864ebd4e29551"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "371ec40f23d4bcecd32fe5a87816a969dabcc8322247544f844ddedb995abcc6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "47d019571a581a0774e34e53bd520cb4c5c82f68"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "041e07d52e55fd53a37c1bb5bdee20704894da363c8678db28326245e55557c9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "32e1bfb35386c2ee3b2b2ef6ffb47d63d0415f77"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c90c2108e67d1d466e1d50fa035221c67fafa23145e1323b347ad4c7194ad5a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fc7beab979c84b68be4122382e45fdc43c43ba33"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1a6c952c1718fb966ab6b28765b925083457f6c6678e4cfb1086b3f08cac0e9b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63a52923008c38fd2bdea6db80fd5951e962eeff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4035cd15b187f8be2d85aa188863b9b58a9578e3924e1a575241ea1f7d8c5fd1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "395854bc5056b5961d10515d18c1406476d612ec"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fcd8c1b5475501ca70b2a83f654c9801b4fa42a7c8d1151120686431e4df05f7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0bccfa663a30106c0211b472719d8cab415898af"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c3ecb871b317015eb2f516340217a479c1ad82021f060bf435f8c2adf0f8ff2a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a3976e2ae59ff968b6793cbff125199a3d187a33"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e4ccaae25c34a11804a26621a49bad5f4f2c8703a219d5500f6a55c0ef8dcdf2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32e1bfb35386c2ee3b2b2ef6ffb47d63d0415f77"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c90c2108e67d1d466e1d50fa035221c67fafa23145e1323b347ad4c7194ad5a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fc7beab979c84b68be4122382e45fdc43c43ba33"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1a6c952c1718fb966ab6b28765b925083457f6c6678e4cfb1086b3f08cac0e9b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63a52923008c38fd2bdea6db80fd5951e962eeff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4035cd15b187f8be2d85aa188863b9b58a9578e3924e1a575241ea1f7d8c5fd1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "395854bc5056b5961d10515d18c1406476d612ec"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fcd8c1b5475501ca70b2a83f654c9801b4fa42a7c8d1151120686431e4df05f7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0bccfa663a30106c0211b472719d8cab415898af"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c3ecb871b317015eb2f516340217a479c1ad82021f060bf435f8c2adf0f8ff2a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a3976e2ae59ff968b6793cbff125199a3d187a33"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e4ccaae25c34a11804a26621a49bad5f4f2c8703a219d5500f6a55c0ef8dcdf2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "536ce84f9f9c4cce024351c451446681c62f2f9e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5fe2b3c9e4b717e620a20bc363545308470954122bef1355020a1f2501a0d290"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1a6cd1184cdc762a7b29755149cb04e16a754400"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2dd47bbb253d185922334152343f8b85d0e1d302321e604d42e9bb8e62aa4bd0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b679430f36406cb25f9685cd6c76a41b26d4013b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "275a43ec7eda2056a01ac6660a5582fe46a0fd67f614a84d34d3a1ed9b24e637"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "7a4d4ff8158180f9a2d1c757f630c0c0f3e03d27"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "babd94c883cef6e0971135fb33148feba0277d131d9bac628035998b0adc950f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "108ee8050d3cbfe65395b545ea01ffea08512621"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6c3d2fe45d8ad903b4fc947a3df3622c9af5b44acf7cb28ee99708e6b696d8af"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "930179ce30511a51a631eea71169b0509c02c02f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bebcb346fd7cc7be3ac09cff22b538c0ea7636cfaa25f9285e1bd003341e8764"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1682b8470b80904dfda3e514cf5bd0fd8d7351fb"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "fac9b9aef28a0ecc579da34b3530c48f23bdbdbb281846edfb7c72f7d92f2838"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f26e6076c9d231b18132dfc40eb1ddfc0c6e7104"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "1be1b75e75d2111f39436ad1763c6afff83e66ce9730e85ea98b001b8f439dd7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1da623dbfecc8de8232368e5df473771f0ccecca"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "0cd0c5ff99cd7abd12eb3ee6a6c8ed2326b0ad128111df7e8d5a55d0305434e9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "c99dae065ac9308061d395fd3ec5ef817564818a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "982954922a146719c15da619de27fee6b22984619d9ec46caf1e21a7598c2a12"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "708bda4f1d2aa02b49befe07a9ad4d85a0ed26ac"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b52f73603f0ec920493a62e78b3fe92dbca6b8bb9e2122b16322d6ecd043e99d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "0a3ce6d8c2ea3e7fe01b54b30c29eca7ce1b588f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bbcc0815e214bab021360cc71b1a1121984a697dc85c5b54d8ea83abe96cd51e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9149f5dfd188c00397deadd51a38a25289f6c175"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "f6ba058d9750b7a5f34e2f70abc45d989dd7de3a5ebe9c186a69157e6fa0c227"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "bbea65857c74ba885ed1aa9ea236bc5d381051e8"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "266ec9761b12db339534c47ee6a974c451a60d1800fbef5b23e70cc8c28ba736"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "518150002ca2261591f5887fba6b1d74f0f3d6c6"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "e3e8e831a1bb6ea329f7283a682cb1e57fc049dd3c2ea54aeb7b71bd88d975c9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c2aef429095859c2798db74846527203816f5ef3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "377f878a7907a3725bb99e8cc35263934efd4311f06a44dfa1e231893dfca63b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7ff23457a36edd446cb89540742f4eee7ed33a90"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e17a04459cdadcb615deaeda7372fb226c149f6885b4c6b2b64148d44f966a45"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "044536e0bd1a1c1dc2e1ff1c03b9a775d49da779"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e97b144b29b8fd8d3778a242e8c15aaa129d92b2ba19db33844672b28887b31c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "385f38647b27cd72673af896c3918e75e8ee2f81"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f85fc369f3a0a574d8581b9e2ce811dcdc24097d876a2cebb8834d6b28a7f39a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2a1aefa4cfc3e38f8d63fbee9391e8b370e1df8a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "76a1c3fa5f86ef4196116fdb01a7c1281508ea6a7c41ecbb5e1af9a943df63e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5a538b4c65148a7d96292c849511c99e5e072d13"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9073cbfd5f1a50ff03d4c1bb069c49dec759ca296d4e7262c0d161d58d8aca01"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "21cb07ee32814826c7ceb3cde2634be265db87dc"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "ba4413cc8329901b6df1bedb861569e56704c805767f6ed5d49e901073fcd545"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d243971b29fe0c714fd5f3f0a27e5d48c5df9369"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "e890451b915cd731e4eea8e17fc3b3c78c9a7c9bf50235f3ace72d6c7a41ddc5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9865b5a9007f15e4537e25773ca79c9a244b5394"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "990ac6ad41908277b29004b3cf3e05b4dc624dfc0e4e4a8f97cc3087c34fe208"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "12427daf6e8275daff7ba6dbb6d02a781301d7a2"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "c6bb243c99379d650e1c217d4f495bd111c15ed43eb025095829250d07ac537d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "83f0a8b6dea312cb9190f02d3ebf035c5af2df32"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "20bfae5a574b87c09d274443c720e018623b174f9a18cfacae6cfa7da1f58e8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7d456a0fe0df79afb3a7c0fd632c4d9eb347524e"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "bd68a5543e3b5c496c36645452a8f4b854b5fbe94d8a270384b7391bb57d2a9d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+3/OpenBLAS32.v0.3.23.x86_64-w64-mingw32-libgfortran5.tar.gz"
