[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "66bcd17ca7766257563aa84009fa45d372fe17ba"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "d7713a0e620224c6a7223263670f393fd71dd43b48e536efd3812bf939086256"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8835b5ac6a6060ffed2bc393263827fcc94aa4f6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5df2755841d60b6502ead0029e877d8bb8e04b1f1620f4410128d75379fc9f68"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "81720099f065c7cfb0b725fb711e0231f866f309"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4f97fa184dc5012a29c9d4efd95f4336f41044d5c3dc693d09592f489e9e5e51"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "b39a8b0b6e72746da21d0d827a0a6bff09ddffbd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "68d01a87eba3bfab8365987fb64bb1b81f61c39fec019ccd03b6778e39017d75"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "93bacab3721e6403920002ecd990926e5d6db30a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6e587e76a12a8a8f4621816ff7110d7d743866a1a4e4781187393fbf564634c0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "a92226d637ce8df0a4eae8bc0a838f2740fe6adc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "80d529c434546f80aa772ad5df7adea1d99b278da836ac1ddfabc633027ca97a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "0cae42c43d3934c9f9907fa1abab0ff799671cc3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fd7f2e520fc8f5db2374c7a0ec21b82f3b0d11f889fee26eb48b2b9ad2faf2b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a2d6d4346ffd9f79b249f679bc6fecfd2ad5a2fa"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d0fe0772f09bbec47cb142a8a139740f8342852abac9ddef7ef980155cf4a277"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f05f577d4f1e939617a92d6c90b3d8a2a3a18be7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "03cb0adc995e3f6078d7da6539eb65f87d91585757eec1ff47ab99db50dac0de"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "31c378a26d3143fa4b8b4ec40993f938e28c97be"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "faa594178d9fc9e1b1671ad4ff1c9b4773f1358352b41d9c71aa6acd26294e41"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "70ae4aad14025a1146eee39297775686e8d43e32"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d21f7f6385071dc0ceb07e91b21e843b27edc48bffee78325258455974c09ef6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d29dc776363803318bac63de4e099b4773811e9a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d1248cc49da0445c3e779caae61c48eb2acf2d7f499dde376ccf23d694e165ed"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f9e3781c0f44a0f78e52d6413f6a85d92d489307"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8407f86fc6f8948f5af23669c184e326916265aad8245bcbc9c40ff8dea71842"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "111e07385299b1241a725a00da40423ba9b78f5a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e71dd91844ab96b72267416ad316e7e90a85f630d5651613386361114fc1f0b7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9a11cec2f579b8d6ef4616185b49566e1ab4a3b5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f9fe8e76bac8608c494229786861530926df2c35dbaebe61791a163fd1c32a38"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56a741bef4db01ed8e298434b772b7c02f658e59"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "05efb5eda1dfc62e76664ece85d7ebbc1ef16655e4fcacd10a1de38b31bbb673"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9ecb0945279c752623ac792039514ba2355f2fb3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4690cf22af424b6ce2f973725991d0919512b281f1b553a3b1cc1b0d68adedc2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8aaa272dcafb9fb516cda48faaf17a212a469374"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "880dc731d4e64c909160de2b20b56d2ebe182eab47f7ff28732c10c96d1da184"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72f8f280e93ea69ab2f92e166253e7fd17a47eb7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d9e540ad29a98ea56f1efa764c21768f7d55cf8a8f77f195c50c5c039388fbd7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "bd4bb6cff216496cf206c9bd294a2d8a74c5ea68"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2df5f1b515283c40b62092775105dc15b475ffbf3f9b169dd550130f60b58ba1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2ca27d914528c87600c4bc0a25f7a5a58b5816a7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9065a01178f1b19500c43fc28fdd2e2d973aecfc22f4dc25e98c45dfbe66095d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "083ff20f91a936865f1423192de22e7f6a29aee9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "28951478fa5e5f18581831941eaed18f904ba36e779ad063bae121ff6c66196e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "37dd5ea9baf9b419add4dddfcc90b68a8b36170b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8942df6a12fb31e0f0c68bfa26dc719e6ae8f20b2c129a77fdac7c6e98fb6e09"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b0d5d6a4fed1eb78b937adf8afab08d1f87b245d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "41c17b39445f3c2eb0407ffa341e6b20bfcaa323c9e75fc1013e2981d8ddff81"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "6b7f968806445e64b9084e97e059f10fdd591546"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e587fe1718008cdf7bf38329cd9eae541665974cb844d1bf83982219888395d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1f4660577dd7225e495b3e0952ac24c8d2b2c9de"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3b315ae76751e0ac97dc36a4e5032b4e9695bd46f816ab82d3d9be2481c5a694"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "8cf68ce664ce154a2476a480405305bd22d349c2"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "274eb21580de26e0a58ee71c1ea306959f3824e7fdf862b2364d27dbbef66d7f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "5a328db1f62c443fba77d7e4d6d0b5e1f065c9b9"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "b491fd8d054cced6b7511692f1ae6fe73a77fd2754addbeb278a96f6f49d7e1f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "ff1776fd647a521b9a24077eb234b590007e4b6a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1a579f6283cabcbaa430be3c80e93444d842d7cea75e83e7ce04aa80bec7de6a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "eecc2317a74625df679191c31d11274ddf80e1bf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0a7c4f7429b026c7e5441c8196a4a4c754a53ece126bd050dae41521bde1da75"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "c5839b73132aa27c3e830bd82c82345a827ed257"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a5ca23795bb7ddfb2cb8e0abb4fa04954f03a293b9e7eaafe79e5ad8ab3b674f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a6dd05b200f1f68acd1f1199a0cd184069fcd458"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "b522954c3ac01197faeb970436fb032462db99f05e85d56a89e7712c9c2c873d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a72ce843fb1b7f722e71205ac6049282d2859fe9"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "eeb8c27a1bda42db49eaf4d71ab64d24e88c6751a9d15b171d39ee4c2f0c6f14"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "dee4aab2f3f6f71e3531d38a2b6e84ddcec62a37"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "f1831d4d8458e014055e8890419a061364e7b3dea35122baa8c73894d4159a12"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7c5791fa97d3fcf6cfdfa020e6598afe86d0f40b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7861bd0cad8aff7ffd61331b9251decb87d1824c70fef011bbf0a44f7f4d2042"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5675ecff821e9801bfc6adcbc8b13550d5ec82d7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ad785b36c3f28256855b15f4ca540ca97c51b813bcbd64938f571970144166ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "faefa5b9c16858da4fdce78d546b72d99b78a5a0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8320e5775bb386d3ff9a176dd6c91844ea67bfb1bfa9b78cf03cb5a0d0ed8f64"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ba1467755614126408672d35cdf6f3d4a7a45921"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fee0df3af7f9c10cd70b5e758757700cc0336e47a012334ce8887c904263f9de"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2a1f926b0e0a1e0d5bec3ed07b6e143d2ded5940"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9a97cf4e0cf83e33c6ee10217ee2566f70d46e617388b6efda0c74679048895b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6181100bd3eeed20511ab537cb483b1cd8c45c4a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c57f471c684e171b8707afe5bca7ef662aba599791bdfd8435de4ca02252cc4c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "91dfd33c8433d84302902422a4c80c5ebc82f863"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "82d5434200d0b739529726d8fd4af1ffb674efcede108913bd0ea0da0bd2604a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "30a5b4420fce5e8ac5367506fd17fa3f1debfe38"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "aa01c98c635e08567edc3b20dc1d51ea4cc27b7d31c382283579bf2f56fd78d7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "64df0b74e18823cfdec9b4d22bced386330356d5"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "f37f007c42d0d062be8fe7860231daf2085e33faef03fe444fd859968b16440c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0621c1fcc18d04d7a268d03b941cde5137aa1a5e"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "670ea3bce705aa8ef205ea320438ac555fbdcba3bb5cd7c31b15d138ab969591"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "80daac6eb74748960bccbadcbe53c109302e0b95"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3b275b2a66c543c173302cc71ce8d77aa5e9d8dc66bf02d490cddd7393093a81"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0de6b2f568166b56b74dbe76a428edd1d90a1638"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "1f02cfe49dddf67a3fbb2a2ef9f98906fff9176cb62c7f9f863de248bb902eb6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.12+0/OpenBLAS32.v0.3.12.x86_64-w64-mingw32-libgfortran5.tar.gz"
