[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "6a661253c2c5687645b94e41603b96f52316bdf9"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "ac12527c694cb3c0fc0daf3c45bbaf4449266c3e42eb90253d3a21af77cc5ea4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9550faa97bbc02127a6240980294fa28aaaccbbf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8732805bd8e67f744f8940264e0f878e6a62dd379358ace916edec66f7fc2aa9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "15571f6bc885c58d3ce6eb2417e47b45184a98c4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a9e380792a502af59125953c59f3c402f6acbfb323b5e1eba2ce689cabea2fc2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9e19a45aab0a7e8d6ea81ee6a02e3769e52453a2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f2af647d1ba5d9583929fe703d0cab064209dbae276c730c8cd0eed023f9fa96"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e9570156341dbbfbf60adaa736ab099f06c23fd7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "346b52595c90b5a76bcdce9e3635669a49f5a776ef02db0939a1ddc55e3b1f2e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "01f0dff7fa934e03e356e5b204b4ddef94bdae9a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "35d54026890cb2b094df944eb38773f5226f887b1d70b5dd67e7da7d892d65e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "eb74ed056d54972bba54c56f2baa49a9fa63643a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f3df337386f5a93889d12cfe70f8d7863ca0ab05dace9769e5485ae379c1e91b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e56769e8308d1a901eb364bd65f7e05ee7b7732d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c7c272caa09671455fed39f3b516d683e74d588dc2ae0feb7cb10eb427a1d1a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a2b17a4d75957433e42804a97c32fe73bf3bc2c2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0fb78446a0d434e2c8586ac412cb12c95201b841bd528e7d9fea1d7fb985845f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c8f5b3ff5790183aeba2ba2b212be1013d0e0c11"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "faae997a0fdc393d0d12d3677ebcbea5bece5a910525c75e74ec2a02f813bb0b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e3cd0dc63b2355ad11e000ca4e3ba37d814662e2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bd63e201c2819236c992c2b4888a4cd916f23461d49a6d4ca991112d5082f033"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24d1c143396a555b4ad027e65f1820f3330670e4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e4260e6884ad2ca035c6a50f8a701288970d6f0bdc2924b548036af76552823e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3544b1b8838da9c31dfd6628219004577db6fab"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b408193ff8da4bc0d30d59007cfbc28fa1425cea5cf6a9529abf7bbe7ebab11c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e56769e8308d1a901eb364bd65f7e05ee7b7732d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c7c272caa09671455fed39f3b516d683e74d588dc2ae0feb7cb10eb427a1d1a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a2b17a4d75957433e42804a97c32fe73bf3bc2c2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0fb78446a0d434e2c8586ac412cb12c95201b841bd528e7d9fea1d7fb985845f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c8f5b3ff5790183aeba2ba2b212be1013d0e0c11"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "faae997a0fdc393d0d12d3677ebcbea5bece5a910525c75e74ec2a02f813bb0b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e3cd0dc63b2355ad11e000ca4e3ba37d814662e2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bd63e201c2819236c992c2b4888a4cd916f23461d49a6d4ca991112d5082f033"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "24d1c143396a555b4ad027e65f1820f3330670e4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e4260e6884ad2ca035c6a50f8a701288970d6f0bdc2924b548036af76552823e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b3544b1b8838da9c31dfd6628219004577db6fab"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b408193ff8da4bc0d30d59007cfbc28fa1425cea5cf6a9529abf7bbe7ebab11c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3c85bf17da920a81dd4a9509178e2f72670cd330"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "44888601d4f7b847ace14c84de1dfc8f046b878dedbea667bbf2e8db97af255a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "50c367bfaeb914f85ea1a398e615c2088e9eaa32"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0f018741318448938f1b2c1f0b4367dd790e70f0607fa939e163fb10d06dda9e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "7940577279c7f16f4be64907d406349c31144cbf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6c158ab68b6b290b5b57de305e7c999af8a035437aea24141ec9df8bde01f70b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d0dbb5fcffd0e779992b1500a358a34eca1cc8f8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0f254bfbdfb12e1a50f38395b4b019fd49fc21bbd27fe4fb906cb37fc233c338"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2742ebb42b871d1ece8afa4c19e65bb5ac1e7283"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2315a546323d069ad2ef85b3e780d702361b2134b08ab9fd03076ec7484249e2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3b44d569b9c1214d7dccefba21d01dae534bd001"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0029b890d8a9e4b8b7fd83f87fd937258a54864474112536dbbc872e715bee8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d3f2292493f574061cdc5fe88cc34d292c382466"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "998d1dcae3a9591add77f83d429b6bdab4969c30a541fb772ee3f4d804d7de7b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "388aea2c39ebb7c17d5991a325d62e4cb31f6619"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "18c4836aab5fa4b67ccfe2cd820715cc11eec1a097aee275243a90dd1807a677"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2b83bbf9c9ddb885793ee1ae7114c08677707077"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "675d7efd6f15f207add218ab193b6543b286d354ead38d1b76fe05466abcbfad"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "86e6cefae2706a815fbbc7e6a2a57d8d38f57bac"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "28c48b260d4e22e2fd70749e974747a90fa2eb28ae381c5ccb1051bb29b2aa85"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "164e3a5bb656cc58a695c72376fbd0c2bf15af52"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a049399c7a386e8f8a2fc0f7de0476f6db84fff8dc6f4bab1b23f3b137371ad1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "8d727e127275dd14dc5c6b02efc66dda0d43c2ba"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9fd35c78b3c18b4bd994ea26058696a3ff754f5f9fefb9efefc0d65b31aca31a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1a85831726639392f1a069036a6297ec4e179e0f"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "1d5b96537d5751cae1bd7ad4118bf1adfda00234d7d76601660c17c7bc73fef8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "12bada5a0174ab85769c5dccb3ac0335a8ec250b"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "2976af6f3de5ca8adde91b9f0c9d9e379778c85d3562ad8f7d8a359545aa066d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c041c8ccea823b9c4a1a9e93d160f0ec4c33a3ad"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "1f014ae5f6ab2a9691952d7fd1f3d891dfd20d624f04519916d98cce702c5fcd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "68502f0d55caf652bed075d1be4b2a10d52a99b9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2fda0268445167f9bdcd11939b2021843a59407b1207a2fad641b84f19384048"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "99b18acf2125323e905e7d4e03e7f85a9ac317d2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "21f58fd1710e029445b1ace2f3c9424fd8db4bc3a58623806d1d3e079a20708e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9203e2207d452a081b44c5aa4d8e71ef5cb6027d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8f3cb5300993ae0bc6a510fa88bb934aa7ee9ec84d21ddef7a0f91d0fc269d4f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "beed8c6976e386136382809c60e1f96c9bc53a4e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46e8d5c3e0bf2f369f3b2e280067482cfeebaa3a4597657b91e1efd530e0e0e8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "bf8c200f3a658274530fb1a13fe2a49ab91bb3b3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3f6d039934473f9faa09d6b0355b421da3dc17a1d246b47dd444ef96af9623b4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e5363aaa9ccddb803dbe8fec6d836b832e69ed2a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a1947a6d597dbce287b55ce29054690d37a2931f8438d6c3a14ddf98f4820b25"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b68b2e6070cce6d92e9ce28c4f809a702581edef"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "8adb9088ac22d1f3a793a57f1adf2e13721459a5197a2a6bb7d220e1cf7a7b47"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c6803d0ec96309cf0b56602cc90d42fe6f547f51"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "29c3b690d7085c030b08866f6551326928085fa9ab1f86e01225439cc12d0524"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0362b8499e5c6aade7b28ef483936667686528cb"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "7c65b97c48769935d7a5021152cb11c99abcb4ffe9afb622176d195056a41463"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3267075607b7c154b3e5e24331c6c4b9f7fabab5"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "173991e8bfb0663b5eaa4a1d44e1343cc6c8b5b51ac364f4ea0d0502342d507d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "4854a8fc8f73b0971bd5c1e1a37bb7096e58682c"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "4a0cd74a0adf6a4a2709f576910292a3e4948e9723bcf6e0d9bbddd6cc3c9e66"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "95e037845dfda22400b4729d31f0f3bd5c16d067"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "bb0cd0f5e7262a245ce38a94910fcda5002323287ddc7a9a5a5c359fa59cbff9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.26+2/OpenBLAS32.v0.3.26.x86_64-w64-mingw32-libgfortran5.tar.gz"
