[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "69d569366cf8b866242ba9613a199a2403a6b329"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "35b764fbf6b8420ee10fd2d9ba3aa0c3d1be363da2e04d42aab2e38b012fdba9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "770dd17056a0340213aa75c22acb43d1dc85ffc2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "85f6fc7419af1e645140545415390d5b4f54621946409bfb6c4cf786b52ab5fe"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "5c2255906dd66815a2e6a742e606723b0d2b4f30"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d5a61c6b1c4d84524cabcfd3ac82d1406f71f41374c85bb3ebc069ac44d820be"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "c7da22441641d70d018938555f87e103c421945e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9b65097ac0c38dea40023abb9872bcdd2fed2504ef17fec487742a6a8c621a61"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "7ec479f9986c1999afb2acfecef34ee11bfcc0a9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b4885e9325730ac85590bda147363934b95a76e9c232f25186cc1386355981c5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "485441d593d5c64524eba2ee10fe25eca18529f8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3a2c3c7e91773c9380f4deba110efc86cfcd972486da3ae8fe11b6ce6409ae6d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "5f9c3f61e65dea43768e3ab12cb2e4f77c207a96"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "42891ec5e836782ed9c441a4a8257f15c4f69c4b47cef4471584bbedefb422cf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c4f14f7ebe990fc0a31a9bdbe504605d0b1e305c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f82a79d51effdeff0edeb8309d3002b58e370909f1b377509358b0e44b28eaec"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3805056c48c7a8ebce70814ad66612c9094d818a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0bff9ac34b200131ea12ad799867c5e5bef8bf30c486186e6fbc39275bf39b39"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f020dffda236d39a2444807625fbb92cb2854a6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "85df3ed9bd2dbb0782c0975046bda37c74412c784c2f46e60f3391b7b9fb5875"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2cf40e14376394c29ffd8fdc8364b47c920c4e05"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "85389107b84fba79138d9f2a7b76482c6a8b833e2df71615c888f889c9de625c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3c67c0b0cc247f94d72bc56b5a8854cc3ec3d10f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "af3830bcb79279b9cbef60822fbeae8e70c47a98893dee831bf0e24e2b988a20"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b6b3b45248c170b0444e614fefbe04cea81c9baf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "339d3cb60845688ec6e13e821a3bad2713ef5cbafcd6a99aa0356d01e2489f30"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "194752f81b1940c8048eb39dd9ffdf785db14b71"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "71004fb9d2ef01efa2967486cc9ae30669a8230ebb0a0e2c006b079597c7b1e9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0117bc3bfb10ace4242daaa24a4ce65ffb49b141"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8530d8383dc7e0b4d8ef1775fbbd8a5cb07306d0fe80a5ed1aaa15c3ed0d3faa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ed7f04dcd792522ea036fcd20beb9097550f8137"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9607fa0621ea715b380a33a2eb32f28d1ff5209fb6710af6b3adf1dcd73bd86a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81cc2c72a96a638063dcc8bc3be5311afcd3b1e9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "60dfaf59b1787afeeea33ded27457cb62e2e7bd79f935315a00a6f55540b084b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6816f323f635a820154cc7e6f6e5aae9e168a1d6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3c506d892e64a7f3caeb600a3c39f40ff81caade2777d8807f3b23efedb62ab0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "825f4c75df4fcdf68e2b05e94a8ada2f4a68d567"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6726cb4bb964d807235d66bb302ae25f5f629d2d0ca8b70225f5560c0d0f56ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b227ea4b4e5b1e48df50a67ae4223e0222cfa89d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "90f293ece6d745ce8f50e8f34865563d267b22788eb0a0891b024b61d563fc37"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "e175519d29018eb49d2af8146156471d3996b165"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bc96238d2663238bb5087730edc68dbd1dc9662227e60c1dd466ec9ad262da6e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "828712d110079a8db872eb0ca6c4480dda0cfd2f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2f8448f2c26caf4377c538996561872b26fe685c075330682a206c9783c825cd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d2c16d3542402e33b7482deab2ebf86ec9d8f0a0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "99d114182bb3ccba31e722eb2c37d68e8eba6b5c67c910ef42d8fb7bcaf2ecb6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "a4a85ec4dd2ffeeeea2f1b3ed3f71b2d4536e0e7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ef287d3f9488e2d8daa00aad7b9979b1c69b408e563a3f523afb9e46717ae856"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "682b3176216a4d371489df6c499d5671751b5488"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3c7ebe5ab6518070270414f6cb4d56da6b028a871c05fc91126f728be174ad10"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "9c7197a09d7eedb0406b41ab49fc319a7da91394"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "0379d1b2c27cfe210767a8eaa5a518b0168322a97d8c3ca12478922ae1fd39e2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d21cc0647bf5996d0f0fec2b52cb045e9917c3c5"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "62700a4a6162be4fcbc550a1b3d9a2875037ef6ec853d114bc78713464c946ce"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "69c65d75a9293f8546684ae03b7356d5d86d815e"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cce186a549447afa35959442189251716cce7b7de853a558e0de8ad527c73018"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "fd7b3a10c99e4f4010c44a86bc4ac76aed8f43f4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "13a9882c9a2159e6578bbeb87d3c9ed09b7b59483380d801d6301cc81c1524e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "f26a1bfdccb1715b9bcf194623386c6e230e13f9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cbfd5888a5368732c27fb960226ea7daff6923b888549a4422a02e0ac1ec8c1f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "77743f0d31841ad644c2e9c3e9967bddc7e4808e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "87c311990c3c8ca792ade45cbaf67ff7c6751250d6d751ce8ab6dd31af5e4d3b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7e6f2cc5ae395ddf7224e7ed1a2e3607ac2e7258"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "e548f48da005fad01831e60e2d5ce80bae298717f4ab2a65f02bb65d48946ae8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f4b99b08272494b0dc612a8e582c36dcaee72c2c"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "1e54564de6e1fecd831a96b9d80d72dd0712b579c13f7d57d4cdedb6c2fdf68d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8647090a4b219b06f89220c2527025d49104b6a8"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "1c22bf4de43add72b8fe7b8284df1828cb70275c235b0a04527d830b85d41f10"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "57e691a5f755d8731bd47f050d1883fc6ae12112"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "866e1320e6d213717917966898b78ea6094bcdf15829065662d8c366520fad57"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f0761f402c57f693853e81979a74f9eb4537441f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "68c200cc8c5c784e3f71f6535f1f081859ad08b4f9ad82aeb439e5ef07f209a4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5fdf65d02c36f95e99f80efd47b461d3011a6633"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d0be24960dd8e453fb224627a31e96885840898044b60d5ec7b0468df6a5d27c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7036b778eb050a8c6a163407a2e6456361541944"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0bb5db92d64e56b1c757dce048c275b5e7af0faa89b4c3ea821b1cb16cf87493"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ae5f7514f7fa2a82e187f93b522c8a1f95ae756c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0eceff12c05ed258ab6c537f6d9fa2f135ee4f1734ea5034de4b6f8dded40835"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a245c1be605db4da5344c6ba49a71a3e6819a7ac"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0fc2a8fb5f3c26399e809280474772b79cd7c061d7fcc71e303e1fee667ddc56"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9e296740c53b9d669ea601c26b31406e2f401b4e"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "2e18503ca812db79fa391885f372c2fc6d71db847db3ec8028ecbf044ef22b80"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3ef9de289c27205bfb041b47de20b00a8b18b1d5"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "5544bf1650e48f80b8aacfcf9ec003cfde51f608a9a1dc56ad2e067de7a1e34d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "50c56cc30dc739d3ea32c0a4ac872d9a4e7e474a"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "5d3856df0aa71c639dab79f85fd82757c7bb486cd39cc925a20df1bad9c8fe21"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f57ac5c6eb08247d62974adf9a4d32f2fff12359"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "7e206c427a9ddb3c3bc0b0344fba564b97e9a72b41b3114fe1659866b8fe721b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "433f45d65f5d97c6150795ca9e26af342e60445d"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "b7f2f83612613ee637bf3462111e6cdadc4274ede09bf0495b64d0d8d591344e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b13e35c4ab561f857daaa0e681fe8f0d5af09325"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "389aa162a79bb8302c611a7e3757634b4b1932ca3694de791472af0e515587e2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+6/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran5.tar.gz"
