[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "a16d074896c963873c7bbe9113f958a86ccb231b"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "2e3a29a6321f20ab10c641227169a9f761f1cacf2b0293589feef599f34f7a4e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "ef26a60d3c865d6e379489b6ad0c9445a2f52c3f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c2e27be85a832c695f48073993e1bf6912e64f4e3c3ae5dc686784c621d2d6a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8fb02cfcd7ed2ed4833a33dbe73aeac72bbb8e17"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c8ab1509c80c8eb430afc99eb962717fe8c148dc9d7d571628a80851fc3595d2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "72ade5e7fa1cdb370e24818647bc585034866fee"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "911e0091354aea10c54c9ab547a641e8d1995cbe23f4b015a31389843693052f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "07e9c4fe016f803811be5c87663f3a3ef79405d4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b63339a91c6952829e1f291718b2ffe5780c86e87bf2d64a10602435b8539c26"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e78614516f7ff98e70839ea2ee03e2282304a8b0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1bf74c8e555d34c7a9512df5059ecbfbb57e655d23a946c8b53c9ae92a881b0b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "16917ba7efddfca5c9ebeeaad832f22951a9098a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8d4e0dafe7b04fe52678c9d12e2dfe41b605ef22431443da43aa3d4bf67bf6d9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d504420a21bd6c023a1e2b6ab00ac7de1be507a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "42f0eedb53c4d676b7382bf3b9f2d0a84099e5c7a8aa1371fda34d809497d27f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ae421b9a178645a5911f1e9c787c120a7dc0b7f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c90ac5458489c20360c46a54c060422d4cee1be99618cbb9a4ea308df18f6f98"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e15c58f94d4ea9a4b6d7041437c428d3e3edab49"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6244323aa1e0e7055262f5a4f3f98b941761ac69e24fbebcc089db78f8289c5b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a9096a8b9625d445dd971d1eba2ae6c13930cc6c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f5d303b810a45705e9a67ac31099ff29223a40fc4e233e3327a4947678097a0d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d721a5d5e0a86741cefb873bc2c45dd8653ec677"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "803f61af2d65fd444b0dae7fea7ee85db2ed2f2f5b48b02eba5680f2587232d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f0ce863a2fc499bcc5da1bff541c2b410ebe7ebc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "debc308d3cc9c961c53dbeeb37ec78316c2c7844d4859591595c2180cbb3b980"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8d504420a21bd6c023a1e2b6ab00ac7de1be507a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "42f0eedb53c4d676b7382bf3b9f2d0a84099e5c7a8aa1371fda34d809497d27f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ae421b9a178645a5911f1e9c787c120a7dc0b7f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c90ac5458489c20360c46a54c060422d4cee1be99618cbb9a4ea308df18f6f98"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e15c58f94d4ea9a4b6d7041437c428d3e3edab49"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6244323aa1e0e7055262f5a4f3f98b941761ac69e24fbebcc089db78f8289c5b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a9096a8b9625d445dd971d1eba2ae6c13930cc6c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f5d303b810a45705e9a67ac31099ff29223a40fc4e233e3327a4947678097a0d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d721a5d5e0a86741cefb873bc2c45dd8653ec677"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "803f61af2d65fd444b0dae7fea7ee85db2ed2f2f5b48b02eba5680f2587232d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0ce863a2fc499bcc5da1bff541c2b410ebe7ebc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "debc308d3cc9c961c53dbeeb37ec78316c2c7844d4859591595c2180cbb3b980"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "ec471056461341bf31bad4460727fb6a6348df41"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "529280434ccfa9dd6c92d7bc7b59bcd4668234e4b675abcb17ef9bf552c5b6ba"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "cf0a4f5cc73003c765c9030be20c613d13ecd9d0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f51c2999ccf2b8be970f687685c850929f8ac738ec9675b6646399860ab4ab05"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "e3218094830809a87f65baca9f022cc8f7a80cbf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "406b406e20fe39b53d85dce8c6b9f99f3a4bee5b4129288275f963c41067fea2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3575369aaac92e6f099ecbdd6c1bee3621121f33"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f4ae5f6556a32b8f8c16a04ecc1241cfb6dd66fecd0508fa434040b7dcc42f98"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2a44ec3d6f16e6f292ac0a64e4c658eb6b4b0384"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2dcc0b8f851a2a3d09924342a642ef2010b01977293d5b9810af8a2a8fd8f26b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "63f636fee1fa29022b1e0d134a6323125be64bd9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "dce1585864c7c12e195dc1fa543ff7680fbf4138ddb3e29d719ee295a6e60064"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2e3732d05bb46362186618081646da44f51804fa"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "b83af1c874ada01272b0420eced59c45ed7cefe3959af748cbab02fc8ba44c8f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "165a65fd6d51ffe93a011a0749ec0a69ebfcdc25"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "e141c589689f06f0e030b53058044fcf6f11d7f8b6aa6db7f39aaa631456715d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "0a54d2c6fcb3a0278b37f9f67391ee55328deafb"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "032e338bbc04ab98a8ecc813d8d1eb3ed0a34680bee6f850e79678e21e2f6875"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "c159aaf9ba1810157e3ca064c2782f2d0fcb256b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2bafff52b677b2cd896165174eb86519187c3ea1dee29cb86fa892231932f41c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "c2c874094dfaf3d1f2f9eb8d50bd22db3b2c737e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "505db27bb326791b81bf51247d13339bad5194b300ed97c97f1603e1f86ae2a4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "10f1093bbb21b95b9a421945a7e549937d174d7e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1abb31180ab8489b97944cb18770b559171b8671bee2bcddfdab93a686d31a8c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "96523aab2be94416309a7d10823087c61feb6f93"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "dd0166087486cfe2010212d1e83959cf2e17aab2cff37b88ad095433a2c71a45"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f67e67f69b2eb0b0fb28cbf6bdea48694a951776"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "8c56d647e411a1c68798def22790cd7e616add08b70a8db35dd4a89198789bb7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "105b3c34d19a1cbd55dc04b277c601674a66b5ff"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "c41b332f08ef492e2ae18abedcf039739bcf0ed8c64c2d31d13b8f74b50ceab0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1fef22b1444395921f02034959e1fc62ec823886"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0685175d42dc74a1c80d27451549f8269072fce3f527d0d6b46ab977816f763b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a445dae94c636258d41541fc6201336caa5ecd51"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5d58439a7548d5ea490217da9644c25b1d7ed6dea9a2d4c7f6eab1c6524987f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b654529ff9a2328a73f8043194ddc436550f7eaa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e4e6c49ff51aa2395cae64867c06bd2c20ca1a18ea06b25a29979ffd9ac69c7c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "32f85d1705ca29cc55724c08f71ebf19c72347df"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3aee1bb7c2e322b594b2a093d96eb8c61219f3ff5410c8fc307dd96c8717dfa6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "052c0cf469dddd4df488ab57e3bbfa70811229fe"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0df61ab1661666ac0d279da132b4dc9daf460a5e2523f1f66d254d870490fb35"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a315242d31d0043b91a82d3b254ae35d1ee94387"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "77a2a762f122b55510cccb1281ad2f2ee4775aa9b7b3aa73b6664621674d3952"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "dad9b1f1d57883af08ea05ceb30e6910a3411833"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "d68cf597a0387883a7124a70fb08c6526648a17e13561b0dd9c7bffba9f76174"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "cf481646bfab15a6c221670ab7c154312d16601d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "fc21e72322154c503a2f76645a51b9716dba23b3d0411e72f27f00c93726c7e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5e221d38cfb90a18d8ae3ccabdbdc943e917d6f1"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "61718cb46dd7b2b6212549be4afbf415003f55d3159f20c2f4a1f3563deffc5d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e71a00e666cb90a51c03267bfd7ae1a2ec731b92"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "7445070962d87d79d07294c4ddafc69390e6ebbb0e45ea40dceb740543d2bfaf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "70ba26451fcba9a5fc7f8e30f21cc48f8ea9f829"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "10efbaf3601243afa7dcd76a4761d843c2b5186341053b1b812912edbd9941d4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3ced0e34fadf9e81c2a99d65937effb78b179d80"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "b2990723183f23213e455b2bcf64520c948dc6c1449570a34012220e5e2ec1cd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.23+0/OpenBLAS32.v0.3.23.x86_64-w64-mingw32-libgfortran5.tar.gz"
