[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "06d57b419ae3f1c9a23479f7af6c84cc9de77410"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "d1745186d44fe0255a83b54fee67b214647be91bcd9e283ae36be9a4ae8a162a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "342907e501a8bf1c0c1cd64a11e4f8348eec4ec8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d07855fa20788fe6b517de1150be2481e58c7382b5fadecdd40871aab6242791"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "026e3cddf2d871c76a533bf45be5ebbcf44c1dc7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "461e0b4dc07ca63fcd9111c20dbb568fa7662df888d0f21c4f014fc69f6bc252"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "a3b64e40d59c7c62b02ad3c68a6fea51588edf72"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "719f56454669ad89a96d8b12979b714fe274fbbac849ed68f981969bd81c41dc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8bbcb6f6da2e9e4f410c22686f7e00c30768aa72"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "29e421583d65eb0726f4f3a768010df66443837b6ef13bc95f9d6004e5933166"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "af2b92e068b81bc38d8f9c02cddbacf50c3edd30"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "468ad32d4dbf2b72382de63b262929ac450df165fcfd735f35db0faefedb2289"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e18719900ce477deaf96b9d54dd83c4f07503b71"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c78bb46eb3bf771dc0eafccb6b41633610c544dcd1585626e1ff5ad3fb1be4b9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e19b65c480411833d595e05aa78d9529d0e936eb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6e717965ee2b800b8211395a2d4e626c1fe92a52c6c8e1807fba139dcc0a24e0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "79cc47fa57cb6298f613a61d8766db181996462b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9d5f85a838c70a4b559a3ac6b430b1d5baec7b809f93772c74b9e528cde7f1a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e5efe63ef7c786a8149af90ca7f7befd7ce8ba2b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "38c91a3cb38ad5cd22c52ac5828cce06f75c0aca9afe92a8bc4a2870f3bc2522"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3287e387317701b5bcd3477e50239c94f1bd0fbe"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3c526b1c80ce9c794b975c94dfcc04132d171f31be1c158bc6ed4b469d0536e5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eed431480d34fe0c37ac63a205e834fed98ea630"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "529dbf0622fcdd4da07e04a0ad2dbe75be7460da0dca862f296e78e5bb72775f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "34698c1114cf18a7a7305d8a0e221bc658935b29"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "349e4e8f30936957b6fd6affb4b50a6b4c6e0a9f1af412fa278b44271f268a1f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e19b65c480411833d595e05aa78d9529d0e936eb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6e717965ee2b800b8211395a2d4e626c1fe92a52c6c8e1807fba139dcc0a24e0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79cc47fa57cb6298f613a61d8766db181996462b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9d5f85a838c70a4b559a3ac6b430b1d5baec7b809f93772c74b9e528cde7f1a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e5efe63ef7c786a8149af90ca7f7befd7ce8ba2b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "38c91a3cb38ad5cd22c52ac5828cce06f75c0aca9afe92a8bc4a2870f3bc2522"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3287e387317701b5bcd3477e50239c94f1bd0fbe"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3c526b1c80ce9c794b975c94dfcc04132d171f31be1c158bc6ed4b469d0536e5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eed431480d34fe0c37ac63a205e834fed98ea630"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "529dbf0622fcdd4da07e04a0ad2dbe75be7460da0dca862f296e78e5bb72775f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34698c1114cf18a7a7305d8a0e221bc658935b29"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "349e4e8f30936957b6fd6affb4b50a6b4c6e0a9f1af412fa278b44271f268a1f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "9f99080db21f9b90c5dc34ca3029a52ccada3124"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1870a7e3117daca8d59c1d1432ec06ee83f622fa808a4c05fd56c3a7c337d508"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2435d372b4552338192ab5dcab54134b4d65f054"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2c85de7c0b5833ff837aeb5bc20374a9c0cd4905c2d0e90f3480ae67cf76d86d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "54b4b5055e650ff6899f772e3090466bc09dc8d3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7b9d26f6907f53a55b06b6b83c61fdfebb8382bfa57244b1ed05b4c5fdf6eacc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "51832a2e35d44ddff43acfa44e1054992ecddea0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9e5d7a9aaa9fb92af07d1767f8a8f94f0398311b00b1dfb8e1e363be39901ee3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "397e2366217926f004ef82774c2204ea6c198bd1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "53c2c3e97cf8c0e63d692616258a69a35d9cd26f2363c565a7278fb25570a20d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "a9e099b312d5c9a500d1aeef946c2a357ace225a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fe9f3ee1c7a1ffce52bd6b7c6a5f7dd76db248afc3adcda1320d14ef82efb8e9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "bf97ed8cdedec5c55bef3d8caf6bd5938134909a"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "507e79dfd2fc06df28d20d77569358878bab102d2ff198a3a56da356315a8aa6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "06802b09208c13d4fca7223d0599c25ad1f96cd8"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "a023b12ebc5a4e406ada65e03c38c3ad032fe6132bfbd3b39fde59b5b5368b21"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "941530d1d8b96dfe1739fc8d36f41442b8a02c7f"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cafabdb5a09188aefc3493d1588f85993dfb332d27f1442238e47a4deac1709a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "4fccf7895a07d3d09cf2aacef290ac746b62936a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "99ca35114a52164e0e4605e188e68b91c3a995895cb8a95699f72cdca07939ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "452ff41514d8efb0916632f12e771e3e07d7e8d7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "14ff9174fe5d48e685ca2c5bdc894e3218b61cdc91798cc99eceb4ab566a4811"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "1b5f33fdddfa16795e8d243714e54048a15a5467"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46cbc21bc83b6732a6383a680da64aa5f30cede31af3b56774e168c20bc10f06"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d083c1436990380cd1699929c4f265ab629237de"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "786e97ca593e4e207ea071a9caf4094a17f7e8631beb222368c201b49fd08b04"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8a27a48525d8a29761b7f1b045688f13dd560814"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "a0d9fe2177880642bd21ebf31b45c7fde005e0776b730e9a2d3f242e7b22eaca"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "57e87a67ffbbc2f31156440afbf4345678ae785d"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "db0030b279718d6509fab5004a2d1fcb92d8fa3d806546381bdbd624f1f075a5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2c5edb153f68c815ee6602f8ad0cb32aeefcfb75"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9f0c8d07c442fced6c0fe05b6eed225c82851e74e1b6877ec0b94f914922f774"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a2fee5906c7630809edb55974828cb4981c8f635"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2cf95bdd10149377d4777a2fa85f63b91e692105c220d064bd8654d30e25b6d7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "374383bd7b5f70f61b529c3982127e6a5a8844d9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2d7d68cadf5786b7cd1ce2e0b7a69b4e7cf466640847ca58a4fd53765f1fdf34"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e4c67b7b8f9936213442d4cfa9a14b83b64a2230"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8a0de5cb4a1131c801bc3fce2efe9f9bedf52eece04e45f447ba03b706d7ea10"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a5ec8eb5fdc95356ed5b789b90b5921d8aca06c7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b607d191d3476a8f426a4689526c0d575f089404a0d78d0f02831cbefbcc39a9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c4c7ed9c896be5a6f7313ca58734917819e24a00"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "149c194e4f011d2436db81a5bb4fa5990dd830da1912459c5f9829c58c5eb947"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a4e44abeb51d4eb77ccc421bf9caa67bb0cf34b3"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "6cd40be350da9ea584dfc1098d6f350229d94cee2d89b2c35444262e9e13d60b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d849f103f2c90f34c0c0f8f7f6f5762b3cf8330c"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "c86ff97de725e902a6a08fb14ea4570ed9b9fe23bbeb5518ec1b401f5e7fe817"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6c5860ed65d6530d09d6176b59d040e4076d5be2"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "f4ce450d0436106cbb136bfa1ff56e7dd6e9cb41058e9d32c9dc73ab841d20c5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9d47863f2538a12fe1acb585163de429c7ae587c"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3c3194de8639033fc8ba93ce793e6d6112db4d1822c7c3d7ae4bed5913c93aa5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "eeccefb494efacd0426c90f840c08f8f1f5cde27"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f10fae04a60dff91ba2814e7ded9c4fb0042956303afc76715ab38d58e3f94cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1c6cebabbca78e72a8563a8e97085c78907aa08c"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "c4b34de4ea633d11a83d4fc11e6516aad8ca27304a8e77835880f387c5ade078"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+0/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran5.tar.gz"
