[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "31d19eabf5d2e4b83f091238933056a8f33b1437"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "16c8acb536787ee6bed8c92fd3e19fe8501c3c11d419332f45e83c9336f611fb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "78107d34c957cb772c7915024d496da38b0b2727"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f80f4c672e49d97b50708119d29ed6ac53326a492d65f472a565a3eb22c633c9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "afc87016b846642ab9ce4a210fcf5f644a3dc242"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "665a3669b665ba0869d4fc77298760b3c97172c4166c4d5bee78075b445e8fa8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "fb32817422cc61e2fa438d0e641d2f706fbcf7d4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8949688d4d6b290aebfa3b09f8833d175930ea839bdd25fd16e6ae111fe67359"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "dd3bdaaacc60fb5be45cc3beb5dd8d4ddcf31054"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5f82b252c7a57d969fb77fdb1ef0f2b1fa818282e6b70becd9fa0b2a8b737e90"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "a531f6e901e0ec67022b948473520dd66aab1576"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2e74da5efa3cb73497c48f6f9f4a7c35de3aa5586fb0c1220f123de6f9a2b62e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "ba2b560444b19c2943fe3e08d59ee088e07652a0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a52f86f4b8b906d92401644979db2ca1746dfd444ada4f9f880936469a9a7a2a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2dfc0916a61d42e09a22cc54369c6b8c29f63cf0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ba1a9886f101043cc5f096af559916c5245481d80e5aba1ac9a34cb0b33e9b2f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a1871af4b6cf40bed9f8fe1026727430d98993e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5e26bbe3051633eda2fee88d3b367efc20223df374a95fa762c7989e73ab00b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2d3fc8201816fa06f9a4fc1bfa38fb13979a1e3c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f10cc1a73dcd51aa13b8a9dc0d73d1cc1d287dcd64717794219a46dd98cb531f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e87c2e29d90fd9a6674c7d91a279f8f65fa4f38e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "160b24288e07de4a207551977b549edb509f55787021f9ce949bb8d586c1b005"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "693d920e7da51b53c153d8edcd4c4f031aff0c00"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e87aaa75d781d63f2184867ee7aadac7caa99a935bd6cfaeb49fd4983d8b12a0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6f70c1c5e77eeb525d3bee55140445d27249b533"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2d6f10a512c24f1389206b4019312837629ec891b3249e5c04226eb9c9761634"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3cc626942a23bc7b88b1f8a75a26501a21b717cb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a851fc1996d7c4a1b8c88eedd91e7786cca2f20db33e26c4dcbedbb20afd12d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be0993db2d11643380c105cf2ceb11df31eb9b35"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6c0ac3196bed6f21e2b2289444db0cbaa9f17113f9fa7191b9415ab0ff33a587"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8e2f8bd68c178eb752f3c84e9e5531697f661c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d8e372e0dd3598678138b54e5d2372aaef55250683629ee03d1ab7819c4a2552"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c1a9eccb169b051c6e0d4276b25360694434820d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4566c2cde6aacf4e02f0c714d3fc858b2b0f20257c382c4e08f31e6c9932a8a9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87b81c5c36b9c47d2127d454f0fdbf7d9cdf2f57"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e89eb21f6c970f01e353e7679d950527b11d2e1d2b316e0750c5fc7add757090"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e9eea19a99f92c3ba0dd9d006dbb00752649c3c4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8e0e51d95f684619e56c4ed1c7b0f3068664804aec3c28fc351df67eab2ef958"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "6a2f259650b9b8a2a4068a65a171461da6b2d48b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e84af93cb5c9eaa1f33514d8e9de089665c359343e934de270dc3bac89939496"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "64219d2cd0e1b7ff47e0a9016fcf8f7dbe8f8678"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "482fe02e21df85dba7ff38c7a5b047ff8e075c16cdac01bf555ac6fc67db21eb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3a74abc8c2a74fac50353084100a3d282d5074fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6b3878524f2e08c7ed0921bbadbe4b561cc3995076d120ebe871bb1234c63839"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "59fa9addddd5cdb2c7ba630078bb27ea9878be5a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d6e013a81f16b7aa734da14a428abd137f33d0b303982f7d6735c84b8e103576"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "9afc4e9cae97a05a61997dc065fadc0ccd5fea46"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5fafe00ecfea9f591a3edbb2796f855cf3935ec2d191e5ba1dcd806458a39d7a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "194d665ca13b500d4f8af5745c8089c597e8a0f9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "df330c09cf66d871a03ca961985dfa188d1024e38143976a2e674e7efd41bb89"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "5a8f9e4486eab2b3574eecfeeeadc3be3fad96bd"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "08e30005e884942b5afa7723a48590e9f733383a2d0677eec10a0b740e794dbf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "08aaac647260cf080dfaba3ca34a8b7a60138a90"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "e7f373ee45b92626ede01abb58236fd8047310f8f0f7221e178539f877b96a28"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "6084f2802aa0e6c5a6b6addc37e07a8ad4f994bb"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f2b8237872f91524b9a9cdf0cce9f62690f69abe14a034c1864156d84e1955a1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "e72e420b751672863e861d4b912aaf8342f9c690"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "68446f2c3a1bc84f5c88e4d0605c855f899839cef557ae61841f910db32e50d2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "def7e45d8de367503204e7da3de1003770245997"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "67d2cc5a5c7e25f0c74b266d8af23b2ec22a2819fc77278878185b543dfb215e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "69088707f41af8879f715a1fb5fe340d0d404096"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2af898db357498c19450fb2f7188365a45559d24f13544ef1d89b6faad376ce7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "647c826825f525e689ed42fb21b21f3ceed893dd"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "70db0ccc6f1fe2d97a6b737423a9203b50bb818f5da36528e1b1232890fcf10a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1298ca9432d339328702130a68fcc03a6e7f444d"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "5c8aacd29a4010be9d1cd066c906fe8cfa4fedf0de6bc96d857a4b7b211adf8d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9cd2a80a320d6dc4eda777cae39d26eea6c2262b"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "f4fedba2d045d2ded58956000a3d41c4d5c5b8df8bb6540ed1ca2b2c1a909b50"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5b7fc1c8b015dd4abe7ca5d177c2db913d5618b1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ad507f1d4040e6be107ea9af8f6f00f41db8bcfd6944d721202586b40a3b430c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ba50e21d89588bdf65fdd53a98c5dbb977c80da0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "dc5dd6f2c0efd733f52c13cf1378f6f2d7037d9abbdd4a43a1297411e1999e28"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fc81eb7413490e81e36dd27fcd6c2052d40fa61b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "aa1e4c152fc3d9b461ce3bd3344cb0e7a22800d0208b5e945d2dafbc960b7f94"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0ea0f17221a37397f7acb9512d8c91dc356a5be7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "28ea61342b983aec08f4cf3804281838cdf353902539e415828a3a61b6e2694a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "dbf8994372ec4d4da355f2eee9ad289a2ab65023"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4670b354c68398367a13b6c7cbddf2ca7081de350be95655d1fdf9f36e2a4632"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a3d31b44dd19d8260c72a992aef9b4e8e6deb7b6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "446f0b84943c3ce698e74e471ba4fdee54a0928e13097cac9a56693297788a1c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8eaae7beb5924060a3ff00e74ccec97afff59417"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "cf227e832c1690783406518abb06f8e9e8c81c2aa99d14cd758eb097bcd71f9e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6c89915a9b9c279e6f96ad4329de4d68cdcf14b3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "7a1f3e3b6626eab576054bf80887e3479f127794e60fe0aeaba21055d93e7639"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2781677ab8a8bf73dde0b8bb007b10116e8f1d16"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "18c6e2d4267e1f28edda429ec45f61655ed56ad7419820c65cabe617a72f4df5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "340ee9fd1544b8383c022709d4b728620672c0a6"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cd913db18ca66499ba41aa018eb6c94a4c1f346575962117eaea8a021efd3f66"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e43ae17fa3574cd239a54a2a828ff5eaadfed39a"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "28f39067141a22ccb952763bf542d0ef01dec7cc734a2a5e3bc7abe9a13e0ef4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7480ade7a4fa38163a498dd3915750874f65c951"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "09d3785682ba5acb40a64b781c7b362dba2fe13177b8b82158c66d0458509a2c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+3/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran5.tar.gz"
