[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "1ed47a015016deb9b01c269e5a1eda11746420c8"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "591623d180f89562f0c098d5907710ae12fd4b84a3fc5eb14cfa14bfeb2c6b1d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "41e7723af6a57eb582658598547d06cb04f672df"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9e28ea7de315ef78b2c3d6716af10c1004f30f591d2f68873e27b6081c5d1ec2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "43e03601d674ea04c8cafe6c99a2207839f066af"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5cd1b26d0f964232ade26ca1bdaab76ebe5ffc68467f3ea2583ca40db9e5aa6d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "55295444cbc4ebe5f524b17a454c4566bc22c47c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a0e56af2171508411e3f9e8a0d502d737c970b47bacea7eb59317e576e5ddcbb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9f4fa2b1dcd389b4e1cf6588fb3454407b1f07d4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7afb0d8f806337203a2a3521a13d3581213e5aebfb64a652642fc1b65d0ea976"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "fce5a82406244c6a2f03636d77f636d464489b3d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6144d499a6ade7ac17ce7f469d9d4fa52e8af05527181cf2b41d97ce66188ed0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9f70854560be40701d17c4886e0ed155186c222c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3c5cd07d1b45e2e6de13c3714d9f3b8c48fb9328e250627d58dd9838dfbb2cf7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "baa5b5c71825514010b713d0b4a6ccf04cc8f9bc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7f3ae370b4df3fc782680eaaf31a8023652899b260b2bc06e31e7e6792fd29c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "405f39289aeb668b6e0a3c7c7ae926744b9c143d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "45e840ec911d36a6891c49c96b8610f9594599ba20407ab964290f5267ae20da"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "566b0a238634ab04bbdac1bbb3b58c8d8ec73296"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c5112be92a63e34871e12123550a8c7037c7d5c9c5cd4fe1399b3d0e97978737"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4ffb4d39dd8b33d4cd59b6030ce5453ea242bcad"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b13b06e222178cbf0d4a8f2d088474b6ce74c033787ac4a288c338634065de0b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8504a59600b92f0705d1565281abc4e184918505"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "285979445ec1584c6ffbc41e51905d3dfa4bf3bb21b20633b01b56ca86e5eefc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3b6fd48eac77a3ad046df878062101932f230bd3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d19b9016ba5be52d919e9f7404242ce5e22ea5191ce998f0263dd277c4a1fadc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "42a29531cb7691d99a7013e9f2f925bab8720960"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "eecce225e549ec303eeb9197111b9d0ca5b8036c2e3e1a026a572cb7d12b545d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5629853699e505dcdfb6d1cdf002a1b3dc7b7b80"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "24b3129e096709d614b78d7c546498b627b7bb4dca6d0c1fe14de570e022c355"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9d1cf306f0d3d934bb530b6fb6408af391af855f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bdc64f93c62702dab9a42e9639cac8e06e5931a6e245c3f5239d7224ef327abf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c02ecff9f5a34dd7944b41b91f55f8a7947a5b7f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6f104502d1cad9778c28e8d05255bdd3bbda0b49ec51188ce3d2a6d26803461e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "038b431c8560ef6c98d6743a4ed255d52584c461"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "80ef0b9cf20e9ccb0c8ee9669d41781b4747ce5b9416e237713c7d7e08bcc145"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3842fcaa9135d9fe117b022d6cdedd1419000346"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "24dd5bafc6e0fba83fa68a78c135d55caec3f650ff55bc7c62713659a8b439d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "aa677777a7676d981c5c68bf86fc1979de7696cc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1d852618777376fff849afbfec9cb5216ae35df35fc948fd56b8d98b0961b31a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "ca3256d5b05502fc6d84154a152ade2d5aabdffb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "beaf4a3011125e68a48caa893f56db5fc093290a09c6d5c3d0e4a8b064c78d86"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "a70bc685a93a5180210ac7f80b342bbaed943dad"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d6712740984af5ba7706f1d57f6afdcf8e5b7535abe3eeeade2e0b56438ebdc2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "23d9f2fcc776b16e06a09d7b551f12e1e52679b5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d85724ae2418ea84fdf3d11793442b157c131557712852a3495935ad0f7b5636"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3430eccb9e56feb31690c371c4889ccaed50555c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7310ebb71221de2e55eb57cedfda918fe46b1b4e53b9f8bc7b90df97c5c0241d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f21372fd36f87f125e43a345d385a89eb07f74e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "01391b9997c6078833c5ef4d86449625bf8c44867efcc0300209c1bd510fb4d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "778c38262b3b17495c8c5baec341cd797b02fa12"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "c2d8c75712d3a7382c69b279f8fb9cebf3d2f8ada3dd2ac1afa39d849a964cf9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "477fb9ca828cede6c8393938eb41eb9c6c21ee2b"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "04d30505f26df56a1df44a5c7b31702e70c8094b43ae70443087d7177308a945"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "00e545abab6ad7e2ff5ea370fe55b7f5184e036b"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3450696777d8d51d16b662939b9729d7da0e0dfc34423b1db91fa40ce8b63266"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "330fbd63fd1a0506e9c15f1145ca089f153ad733"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "21e41410022b12045089162a43527c0cac9448782ec4ba10a9c0719b401e5bba"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "528eb8d8f8f5218da58ea11d49675033f1e6da52"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ffc6da0ec1c527f1e37fed1d6d016ee2d3f688d74c5193bd2c17916dc8ac21ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "7a0743a1cc9472437018946f942172cfe636104b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d47e878ff1d0e7dd44b8488929221ec484afbdbd04a39261ace4adad8cbd3332"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d04861dc41b6994edb43f2d0463bf3bff59cb800"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "cc9a0263831fb54ff8d94a42588497b33d65b6681422c097db62b04b170b28b1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "38d25d6d87ec94ea8c89022529b8538bf00ba44a"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "9cc438560ce1b5f18f87739d1def45eb9f4cccee48ff48ada6564e4ebb56ab95"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b73bda4a020765edc2f44997938db00a61d75b12"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "4787b35dfd8b81658d06c03d27bbd3f92ab9258cd1f447cedda089c4bff29a88"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e133e286cb41bfd4e4dfc4ff67d5d2fa16c8b871"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a26bc32d0fd7834c0e635267b913f006463872d4f1c390a2e71591be0450d3ae"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "49a4b88ac81c72c3fac3175b67c528e4416aceb3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "763d49b7316919a309f33b87cc5b933029ab5d3c691be8de25648044b2070e84"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "01ab59bbba8b669b7688735aca80cc9718226c65"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0d3a9c2694690acc362dba411e1ea74f9a12dccaad48d1111f6e5a7f5a7a09e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "80630b907e0d026e9807bb56615f4d00dffee449"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5197075cb409c6c3ffe40bea07e3f6fca2ba04c4f5ee27e4c74bed1cceab0ee0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b5703dbeea2829425bb034f66541a4b16b5f1bc2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fe9e921c4eb65c3d48778a2215e195ddf77915461c68f90578b278cf228d68cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "efee031ca5daa6ae9510ca7d5ebfd79084e54eec"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "aa195c6285daba91d7e7f32c71942b99917f72823a56c934697baf5af32aa5b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "dcde4a213a7664ae2b16280a8506e9eb99e58f34"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "061b9cd05a781caffb9f3e58a827bdcc0568a925a5dac9fff7d168dd9ff85a52"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b2498ea14a415d275be403dafdd3e1222afdc9d0"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "086b5022efea4936800a2f4079a46cf3c331fc477ecf3b5109e0f300588a2da4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "14c17f74c66680585c4df4ba505c82dd0dcbdfd6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "a8fd0dc6d744e49fb5c6b7caa5f945a1a122fcdeb56b959c77d874e0eb35cded"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0f7e0688188db811e4ef25dadcb1a64dd0161165"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "83c161e9abc96d62e9b26a38a9178109d4a9081000d8caf5148a33a366fa05dc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "4928319de026f44e3ac605fee26941df3778a72a"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "d274e0f89f44c256091ecff4d85d4ec90fbdfe1b734224072281ce6fcdb0351b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b94b7302e641a558852e5c96f2155f703658d197"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "720cffd80a07601dc683e49f0e37b6e665e6105d6f4179380bf04f24e6efe88e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+0/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran5.tar.gz"
