[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "0fcf4a9d05a8117d9311f0b1024229e1f8fdbfa2"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "033f75ae76282a814a01fadeb76e70e4402cfd6be5640afa1e264252d7d2f92f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "c9983f12efc99fb1ad2458dd5e855c975c372fb7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cc82bf6b33cbabec5d48bcbf66a1e4dc5f45a9fbf4b1b191ec22a640092bf1e7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "d357f466fcd7fc5c430acba373448a1c5cd21bec"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "521558ce249aa8b76a9645b7815dff087af1dfcbb88e7ff3ff9c1cab8733dac9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "3ae43fb0befd3ea77ed3a5f76209cac59f4a076b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "09f5996aa7be01fb121e641b47f7cf39930480d686bc4616730a676f4ce5c2cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "76cf45a896b0fc79b454339068f1e4443f04ad9d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e9dd1146573f8d298b3c004b82c2bea415b2e423b6432a3838b4150064cc2db0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9545a2d81563579a840ea94bb2db6eee3400c707"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cf1fcc7c677b5327ca1960278bbb6432a53361690899d06a103fda3305aaeac3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "5bcf0a9d2658388d07f8b1b2424671b0c745c8db"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "84ce36c4b2b8f02f27103287c0f05c9ac85c75bf84387b6bd89d0790f2449ada"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "686260bfc3111e6db4999de872a1fd675ba21f7c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "dbed1901aa98d7144657b79f553d0bf2ca4bf0e5db8b4fca30702ac80381213f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "811c8ff40a26df15700aa55d9c58fb92d90763f5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5acb7bf46583743f5ee20caf669a66d891363325e3eeee4070883e91aa8ef623"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "adf2203c02b539ca4adda7e220163788bfc0e314"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e567eedea91c85dd79c23e9e65be5e88a266017eb133882ef2cda6a8777987ff"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b12f497f7e095da12a8a1f70829eb890de852886"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d586a54fbb9cc061aab10d0e627f5426f4274e3f72d000fb44cbe8a918a39346"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "98e308a3a3a92da33cc4aa22283bed330c450c44"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7f84027516f3935eb8e6659c62999381caab0d4df10aba2ec1cf2c978c9b269f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "158dcbd04cf700287a36a0135b278a59ed372392"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "69c5d50441ad7702a0eeb53e230007d3b8b2ce26d35625fea9e6c241b9c8a0b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "686260bfc3111e6db4999de872a1fd675ba21f7c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "dbed1901aa98d7144657b79f553d0bf2ca4bf0e5db8b4fca30702ac80381213f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "811c8ff40a26df15700aa55d9c58fb92d90763f5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5acb7bf46583743f5ee20caf669a66d891363325e3eeee4070883e91aa8ef623"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "adf2203c02b539ca4adda7e220163788bfc0e314"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e567eedea91c85dd79c23e9e65be5e88a266017eb133882ef2cda6a8777987ff"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b12f497f7e095da12a8a1f70829eb890de852886"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d586a54fbb9cc061aab10d0e627f5426f4274e3f72d000fb44cbe8a918a39346"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98e308a3a3a92da33cc4aa22283bed330c450c44"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7f84027516f3935eb8e6659c62999381caab0d4df10aba2ec1cf2c978c9b269f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "158dcbd04cf700287a36a0135b278a59ed372392"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "69c5d50441ad7702a0eeb53e230007d3b8b2ce26d35625fea9e6c241b9c8a0b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "8c787798bd19da94c48a9cd0d607a72ceb967739"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "30d69c59232e0290b35c380b4f5fc4fe783fc0c498e258209c659bb2059f4b88"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "9bb328cbcfcff6c5f971fdac3006b58043102534"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7bc62113fb539819d68c68534616a02ba00df76d8002832572b8e8006f7a2b6f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1795c9976e51c20fef972fd64eb4793b37743b9d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bd47f4a5982584b58acc27b37efb043a6723142adcdafb4ecffb8c7baeaf6e17"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3c00fee49d3cec083f3817523c146bcc72c124c9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2de5aac09836ba7297b27b1d67259a83a16affb00cedef017f7c894197295f4f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f42504e1d35ae57b038a21644aef4625f2ae0351"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "db5b55169a0de732e378e48105bcd5c9ff287d9e143f9d6ec71b8935911c04ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2e55d0eb62313e181fecae4fa0601a5245c108a1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "186d4fd4b5307d1c7fded3ff5ad7f088c3e910355fd1e02c10dc63a613e9281a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "c213e77fa756501c5a16d4c93490c600f384f5d3"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "5340c6ab577f2b95aa6cf9934320c34ba6dbd3cf4c849003c75a0c56aa7c9024"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "56c2ae6acade8932b42a6ef619a195e708cc9eb1"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "aaea9ddb42d53bd32a4c80551ed1eca43c0927aaa13f7f9147e6a2fd21e50a9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "0082373f376467abe4279e3f14aa3c0ead152eac"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f400a0e7f9772df1db6c089eab7b9af1466c57d4870554e82dc376e416786b36"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "74800b99b4835d84c6d1ea8ebe0c3ab234db20a4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5c490f7eb3a75d25eabb5af6db6c42bbe1e6b068d758a7ec0d62fa2fc9b702c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "ee8e6c99f8a3c358027f57dd2c7c9331525553f1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b50294d624b523b4f73103b999b250e66fe8a93454a31a679a95e249cc6518c6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "a08f015786be42404f3913c03f5fe5f849ae1b34"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b041a13960982f4fcddf8351afc7732469aa3296276e52844826e669c58401b3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "76a694a1c257d0e443067b3db93b839b43a63150"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "2c05a7fe7aca336966766d8c669651c783c5128639f0baeefd4cfe7e782c54bf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "cc598da1b32cef0c9d49d3a0e6af537bdcf031e6"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "39c0f150818ee3d1d2dc6f5dc0176dbd67d22c3e4eb02d26b6b5e9b230f6a652"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0e371f89c70d7010497f3c8900131c707261446e"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "629655019419ac103f176ca21c4e28cdc7dfaebf972d8ec82d9474c8bbc03e26"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1cea7dadd871ea28d499352710a95e9dc72e3deb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c250e2662d03eb590ac0a1dab45c634f2dfb1c6631d4d71190086d51b3fdfa9b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "215fff6fe83fd350da74f3eceb92413b7f808cdb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c45e993bc166a3db15c31c2760dd8651c3bd0a2b5c9b85308ca9ffe31becd4f1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1a1fc76c45086b7423b44726276d197bde7ffea0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "57ccb3b0ec09890bd1a3c566a52eadaf339e2bd8f9a94881d4e65bb04c8607c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3add9c71fdc280263db260970fcb1885ee7851ce"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4ab2522804f3c34bab00b6dcea11ae62391ba20cd794be98bd6d7c388e2dc4c7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d2838314cac004a49625b6b6be1dfceb65c2d9ef"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "76d8922dc0e94d049d4f50b2342d0118eb5a14cdaf5a36a92dafc4839819f6f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "397f42bf7f621e23af0eaf586658efb30b05d9e6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9f702eda3f3690c10b134692578116edea2d9be182d6c27c93e12cf70055ae87"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "191f9e0b52eef79d9a22088d121568a437b7ae16"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "f3895d43f216f1217f7029b1944845ff04efbd96459e76270d92f6ff0b9093d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "29ee0a197e92652824d26379422a3675f362888d"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "7110ef5080fd08ee69cead35caa61053aa98309726085719469964764ce7ec54"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7e52cf8c4886829634ddec5f24aa4ccdde57726e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "b4efaffd9973b17a42bd812646ee2bc889d7f7148bf733adca4aaa2e99a548e1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e3a1e957e8041f92705baaef1f61072adc6d755e"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "21fc738ed49e361503cba2c1035d76f0bc84bbc9c1260c4c63ae2f9dbf657061"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7ca3b1141fbdb4679af84cc2b47071f77b7a78ab"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "8f9f1e33eb2f51731c24c129e8e98ee465d01043759804cc1acaec029c175f47"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "32abe1430b88bacad007f61d8d8221cfb0033f42"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "bf1b002cfd712c453a3993e4913e72d49684cbfa96776f5ff5217bb9cb124646"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.27+1/OpenBLAS32.v0.3.27.x86_64-w64-mingw32-libgfortran5.tar.gz"
