[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "0f6c5dc35bc0c913cbba2d6c0db8ce4caafd42a2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0bc8a3e9bb1aaff6b3785b3e442d9ff92275c815aed2224f33cecc81bc7cbb28"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f8520395d4dcd8a3633625f59e1be0b18dc2168f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f555d0c3bd30e780dfb4f90ffa9f7ca0436424ef9145657c6e51ba0f13ab611d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "207138031efe238650675948b29621fc10f08ea9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ea8926152b72b3d183f44196f725da1b2142790c48b8bd3c733486fc9df8d205"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e2d244acad39f84137406ac6f568b789ee4080b5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b0b2e3c4c7ca65622cb5584a9d8aefdde10bcc4a492bc21d99824b293ea85dfd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e2d244acad39f84137406ac6f568b789ee4080b5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b0b2e3c4c7ca65622cb5584a9d8aefdde10bcc4a492bc21d99824b293ea85dfd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "0b27a25bf39e02e91ddd624c35a25d4aaf015dad"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "adce7a011822f32b391a686d3c4cd8803fe3c39dd8fd124c25e7dd7f63092582"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "riscv64"
git-tree-sha1 = "ad7f4c941024687f3867ca017aae3f04c35c0bf8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2952d7a0a0cfe76ffc65b6e50d7e6c389b758d78cdf6490fa945e60600a5cb54"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.riscv64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b3bd099762e10f1cd0b5895b00145ea4a1a4d663"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "665c0b43c319b084c8adb8ca3e8426ba496764665b8ab707e9503ba28b186cd9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c9e792192e3b91a9b17229fd6a157ae581db01aa"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7e4fabf78141c95bc6343ba21bd3015bf7d7c3cc5c98c98b92aae779452a7d8d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "550c3aacdb773d49b72e1cee032b5c36a71c9a0b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46c0201e6dbcd149830c27ac6ad31c154faa44769a8ecf8649169173220d1673"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "630a444c5d059534c3ae8b7b6674599db2a18fcb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "47854edbea54c06b1e48aa244abf6d9a49810d06816efe8cc12528ebb9a3e412"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "630a444c5d059534c3ae8b7b6674599db2a18fcb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "47854edbea54c06b1e48aa244abf6d9a49810d06816efe8cc12528ebb9a3e412"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e4a7c8aa43034a3efe150caf6369b7b15e21f4a8"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "7b7083331543dc7afab39c083122a197e7178921d76b6a7f43787ce5253ebda3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "0e97c2a2cc24025d376efb2b8c0dc80f55827dc8"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "7aac663ad560bf16356a42c46b875c92e3124fb0cd16385f635c1bb8ed2cbb54"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "df7e5440ae5850d05a15a1d761769ecece3bc49d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "4f9b24b336759f5c011d13598e4f2ebe5a01a5c1be1924306fad0bdc43595acd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "7da3a379c6e01b6b8dd53d037d48b7278e6135c5"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "2fb19208e2e53a9973be2683e19527b2a80d516add1d74c7856a82794e149325"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "a5ebc7b7666f6b8af34ec4c6ad47b75cd8897933"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "7f93a550aec253bd0c395ee6db6550389a61c0fa16e2ea8fcd8a4f4f37c35861"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "62b283ee2a44d1bdae58d753dfca67810645cd01"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f866ad4af36b01d1dcdad3f62db369ab05ec95fa62c698701c623e8ae141be11"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.32+0/OpenBLAS32.v0.3.32.x86_64-w64-mingw32-libgfortran5.tar.gz"
