[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "05ccd97bd590cf4d2bd16f27dac29dff33bf7ddb"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "860b292195f90cc07c2c7b533e4b0413c9573ecb98b0c2547b9610665854801a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "dd82a80f88219e7ac08060d0ab822b6ae3d1f6ca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9aa610c6d6af3e7b4695ab6a2a7cb07cb5b1d1387080ec278af6f869defb0a26"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "d00ed83c8591d2bd226fd4fcaf2a56f2871a6ba1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ef8f45884f4afa7316eb3857dfb506a9e4eb9527a5dda6d4b2be75843728d114"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "1a3f8a4e006fc5725e20d780a49194f05076d404"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "509674dd9a3ef62c0882ccc2e4f68b851a183b3f055d8b564fa9fa8a2dc4952e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "111e8e017ea93e81e40d3e96a15698bed608803c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b990c6710d5c966d01ee32df35b0731555ec841ed9fae991f6f9d8c352619488"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e0beb652b287151656865ddd9d779bba2bd5cec3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9d4d4507278b7abe2efdd34593d1b41986b74e3bf09336889a6228cc1c8f14c8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "d99750a4507e96e5364516b4fb795d943a075349"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6a5b2096a085254a235938d9b67e258527ea9384305da2fe727590fc81d50ee7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a8bb4cdac0e45a9e28285944af2acf431bce57c3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b4b682a66f989ebe6f7ce3574dfa5e2cefa2fcd13bcd62b66613bfbffa4f72de"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0c202b514edc16ce545948a24a67051f6572618a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d54050330ef8ff6f3427ced7308222ccf7ed7bacd71b70e77731b35054630056"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f6bad183b45f463ca51b4b638b7db2854b243739"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2a3a83d1f22528f78327a18e3418074fd730c5a5d37ec1544a315d1219c8be93"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b6576c05f3720d69d79cec04507163eb13afa0d1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bf768af6ab9a874fe429c2c241c45070c60c8520ef41a78525ed686b52788091"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2cedf93a23fb149a885045cb2a348ae3d0cc3ceb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "86ea4bb9d0062f97ac73f96d959bafc109530336f240aa69f0ec0abaf2696573"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e7b0dba80fd258cd6adda41258ad71c12286e6ff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "31c3e134b94c9eef991d19538582526243d22cedcc3005f00bcf1dd8b506e1b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8bb4cdac0e45a9e28285944af2acf431bce57c3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b4b682a66f989ebe6f7ce3574dfa5e2cefa2fcd13bcd62b66613bfbffa4f72de"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0c202b514edc16ce545948a24a67051f6572618a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d54050330ef8ff6f3427ced7308222ccf7ed7bacd71b70e77731b35054630056"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f6bad183b45f463ca51b4b638b7db2854b243739"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2a3a83d1f22528f78327a18e3418074fd730c5a5d37ec1544a315d1219c8be93"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6576c05f3720d69d79cec04507163eb13afa0d1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bf768af6ab9a874fe429c2c241c45070c60c8520ef41a78525ed686b52788091"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2cedf93a23fb149a885045cb2a348ae3d0cc3ceb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "86ea4bb9d0062f97ac73f96d959bafc109530336f240aa69f0ec0abaf2696573"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e7b0dba80fd258cd6adda41258ad71c12286e6ff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "31c3e134b94c9eef991d19538582526243d22cedcc3005f00bcf1dd8b506e1b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b18114f29543984420c5cd768cea56720fd06e9b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "992a3dcb7ab6c5959f35a528625faa0b482af15b48256d869212ac5b35e5e4d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "78b2177e044d0703e77ac3c2b5a640d427582e5f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6044f5c5c72ca664e621aa5a8f9cef3a742d70932957def07d0dccee71026fc8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "7498ae29123072ab91afd46a773e49281ad73b62"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c8635d45988e1d3d70daad6a7b7163cef2806a4d35470f70fad17f744ee4d964"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "c6b8734773753251410ba3f50d2b986b83a576ab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3ce3705864a2be286a0b6a2c7bb4c93d1b175b4749c9889bc32cc7cb14b9a08f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "46874a89fd04d86438524b05839273e30e3c0fb8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e2773f3272a93b23c97563fec4c4587f0f7eefa28c611322c28c30c03288322d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "60ade06ddf75a04c3caf302a52dccc666faac4da"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ea0e8cd87e8988248be898430bca54f428929ae215fdddb408862669d715251c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "048cf6e8011227f0b04a6318a1c7e88a4a00c0f8"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cfd9806cf5204a3e6bfc2460388d78f1cd26d655a9e7dbc02cb8fa54ed9c58d4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "8771a609ff16cec00acea3a0c0ba43d3253b19d8"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3257a7c0d2ea17ce3affa3698760cd4577fc510875ab4b8dd5e5aa67a2f54616"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f8b1cee1e7e0287529bab5dd5aef19fdef4a8372"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "4b0862730d56224776e88949a721393f38f56f4a309160e0988e2385296cfd26"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "663416dbeee8d3cd45262bb743c8fe6b914c9ca1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0eb0ca7597bd27d24c911015cd4243541278c3a5cd4405357d8b2eeb7f85c6d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "13cca086e85cd00b2dad7702a556cb6abbc2081c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e1b7b3b5443a107c5f79b6faf775513348a1cbf4f1901d3d44a9a17fc496d937"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "fa88bc6ad8394000e32f602041fac50c40c48edc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e154a08ada0c00f73be848fd5f03bede4baf463e8ba330771f135110f759b15e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "392364f3e0f00ffdbfd4af0b2b4b1ed8c09739f2"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "4ac7fd261d084ae346cbf070830f1cff4feecff51514de05b6ddf7f922efdbdc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0d791745410f241577f9b3ad453b8a38780fd96c"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "9b25de2956bf1b8ae07f3b0c08dffcf83c3cac4f168b678509ca84b7022d8936"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0744ae2d1c3717e4423dbe3e4a628338064dae7f"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "e1e459120cf60936d01a6905777b59c882cdeedeb71168ec21a7b65c8971b204"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b428b4b2650076f430a5878f1890bfd71baa5a81"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cf5875449cc29f8d432462802970895872ca225e2cbd80a1a314e840bb67e6d5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9c769011219084c8d0e2d744407fa39de7aabbf6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "76838509d375108c7d60a3ef002c4e4dfd9d280e364e00b0a605570c5abb5773"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "78a535798bb75a48deacab806f9070c01c8cba6d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0406f2354b49220b9c7d1295f7ebee03603f9cbe24397c1d0b97772cc929814a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ff8f52750a5d9a1bccfcdb99fecbfca419006051"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f9f70e75815246519bc4ed43f0e3d54ac3f5315946cefeed67a43951253c76df"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7f7604460cc47b1fbb482a6dd3e97da6e3c62595"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "26e5d65c908d893719333b7f4bd70484b6f08a3d054831c1a5392ee6914d144e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ac8bd7874c1a847aea2cfd46d3d2d9f22a56d8f6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f9a61c7b8142e486e387ea62db317684490356203bc3ae37d580c9fecec9910a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6e08ba079a3c0a293b465831d772661680fb514b"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "a400dd2a03616ad1327bfa8ad4f59d26dbc7f95d2a11af99716d122b6a62b852"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2761346cad947f59e8b76ae8f6e3f61e03495988"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "3633badc73fd1bc6033c276fc4ababbf660334045442d4654f2de36a1141e534"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c7db0b9572cb7cbb87d7a72fe332ff56164d13e5"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "9557aef809425591567874d82c2a9022327f788b6ff950cdc54a4f3b52fb1db1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "bbd3d8c09a0ab3a863487097ec6838981efe71e9"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3d4ea0285f876f15196a34c49b32b2cdd52213107c1fbafdeaebe98d3fe697bf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fd62c9e2f126b057b655d418a403c7c999f37248"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "de770c81ce87e266f722aa5fb987d6a60145d7172faa80b2c1da4d52a89c0d52"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fee85570d5e50345dc3703dafa6c9e8fb8885ff8"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "70d487ce1be2a4e073ad16ae236ade1dcc432f34a5cd9582c9e57234fc893f80"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.22+0/OpenBLAS32.v0.3.22.x86_64-w64-mingw32-libgfortran5.tar.gz"
