[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "d7ec4cfa5558a8ac7d54f64a5418b7773c3f3bb1"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "02e9b7f65cf01673f7bb1f65c3f8df098dfb2580b852145e66bf8d5632d18b15"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "5e8e29dfef4bb4819f6d6fb2e24c7cb04f685680"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3a7f9a22c2707e8ecbca5047ac13d11f1f320d41a137a3ca42f00a0ba4c408c9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "489a01efb4d068659c118bae25ab0d642cdafda6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "32e0f263a9f3aa937ded45014e9c3f145ad0dd77cc151c00f284d5dbf4d3504c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9c63d56bf2f9b8e42dddc361343b97fa9cea5a7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "287a459b9f2306763e48a9a23cfb475be4cf0d3bb15cb01753a799c248c8ca57"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "067bdb3369e7cb17728cbb259003f29138907cf1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "12c6e861abdde84a9d24c2e27efcf999da4a354f5f016b756d700619dbad2b1e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "2b46c1d851e2a415bc8e3995e3f25ccfc2b803e9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "196e827342827ff2ef026855a1597474a892edd8e1334a694c715610dfcba7db"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "0841e526d29b3c4ccd98a7a9a36af7ee523aacc7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "01eb913f375ff0889809c45a46a5603589e9dce0781c737fd63c089b5b9dc12e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8f3a1bf5584a673e9cdc56dfbae850e11dc931ef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ffe544d2e22f1f67d93ec43fc4e849f32dadebf97b38050f9173432294f74bfb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "57110f42019743cdd150e795c8c93adf08ebf1dc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "52047787f38b74587cec04cf2f97ffdfad900781a208955e4961720280c36ea6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "de6f03d6b8e4daf441dfc666d138302a4b0269ba"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "40a899168ea22d95375822457ebae490405d7036b70ec771714dbb3453180f51"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fb0681ea2e031762dc7ce8735909564e55c82454"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5aebdf10b8fdca65921ca038c776b1646b6940ce173783f26c93e55bf2bd2503"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "207f81e4bd2d0a2f60bc7e33c6c9092c948b97ad"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "958bbabf0be622d6fc8e2e69578a496e92e1f80a6d8e811b8acf0d1e092165a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5833cd2a19b3df6352b081051d1a45f871625ebe"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f934e2a43a75a99733df555b346977fb8e9a4d9495aaa3308e92c04f7c308a91"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1dcd84b0fcceabffc9303c3ebd0befdfbfcc18ae"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e677e1699e83539edd346865cb8ada7abe05a57b6e68d96c8f26a271e73403cd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e29dbe4105047aa517414bfda3a987420d3192be"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "65c9b34ce5edcb09516fbef1147a9fe3fbf18ea068b3e18fc4b5d41be14380ed"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "794681ff256b75610fe746475d623ff3d5e8e172"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1bbfd2e1898044c7eba2f073f309803f5334d41b24014d851d736bc11583b675"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db2fe1a7366d047e5692a78814e3e511c5d0f410"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2bb141dfe75a6eea2495cd4bbe7f9243350916ec9d60589c55d07e6ffd79dd0f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3ae174e78bd262574d00555f0108a71f9f46575"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a6feb0b7ac98af0946bcf3b67c30829ec8914ed3f88e6ddaa08d2ad1223eba8f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0187a22ab33d22bd8a034b6844eb0b7b9558958c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9a8b0be2cf8f7b3c48320bcea0dbf8c98cae9fa2cb2950ae627782bbe7c6f7bc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "4b8a8d3fbce619d973bd0b81b05cda61167e343f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d6b60da834d6e3fdd5ed60c0cd11edf3126798d11afff7c39d58a2ab994e7997"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2139f82398bc772b492c97e4fd1ec72f772acead"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1ff9c1f9a9a071991877fa7af45ca93176caa997733bbf583716bc06c22659e1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "fd54e6c53cd748715b17a62db22c9e7d090e6042"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "db571e9189b2c3725ceab8a738478d0bb2ae1e4c955052eac8b5c4d00d2a76b7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "77ff67d8c04813936ee0c263e0cf111b10b1704a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8e97e814d2ed6956de9cdd4c435abb3ab90b156860d67ab2929e3edcbad139b0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b0d9a92dc98911b476c09f614bcc3b76fee79700"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "801c386218b88bca6dc9aaf592870b8501e7638c0680ef0642d5a2d89b384703"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "463a3dc437e9809a6958e0c8ccca897f8cecf7e0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5190897c72cafca4456c2d8e1adbd319c47ffd9b6e86d6d9b8fe5a8e45beeeb1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "97fdea9196de43f44aa78ac0f705c8c17e72713a"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "c61d23f259c9e8b840ff4604ddef7754f49412cdb9efbc7bdacba08ae698d5c7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "4e449101d201a2734149f9d59423719e4689a386"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "67c0138753e100959f7de194ba9298468b11c7545734e7c3fcebb4d7cffd3391"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1808369d3a10ccd9b21c0ec7b68c8afb8f739b80"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "9ddef192b96cc4ef0182455bbbad5d27cb348c9f9ea542ad747f088296d9b5b9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "c3e8050ad28889d16700a00642fc01f91c1ba9ae"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3c597d51c61551a2b83a8c4563d01f6b6a75e90fe245cf321424a12e1da4091f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "aa5c9d950098c998de1dd4f23f16826a47c080ea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6059ae5987ec833c334c787988c4781ec6c0ceefa89d620954bf5f831230e510"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "aea01ff97c399ac8acd42d2d6d79099226999d45"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cf0fa4b340c0e07cee0f02022445dd1ce13d21b86a164f222c7673c249f3eb50"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "06ada84af1a62369f2d4c795d2ab0e89b3372275"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "44332a3e2f3d8351f1e29c3d0e6bce04294aea3970b670ea3bbf7774f91fabaf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "4ebb1368465281d712e133a971343fa2fda1c444"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "2e3f4b67d6c3bbea716015f79aac611b4466e8ede6f67083d664a95e421c1757"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8612a410ff84df9e4ec328aec27bf6ea6d424c31"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "f6420672bd5ee6ef2251ba79c83bffb6954e142f82a7deae848697f72e127bf1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "cc789cc8df3986a244c10093e4e1fcd1bf44c574"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6fee860b645b1b1e2ab8afa40e86b67bd6a6929b94182d391f7285640706b4c8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a83c6f59a8af91979044d74b18bbbce204e791d9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "caf26b0947542113e0d61a87c77841faf4f3613ab89c62bfc5390bb43c98dcf7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "198abd8f4f55bf08c6f84a69e2ad59b3899c9f92"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "48db1bcf0b0ba18ef89b1ac9e93b68ea3a8171c62a5f2a11c3c5fc5d8b2b5ccc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "743fed8a0b5b8eeb276d74699d165256fa4557ff"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "992b2cf88941708ab40ec42724268cab00eb2134d2f121172a804e09f3ae9961"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d4926a240cabfd123f6ded81446b4f059ead488c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0670d817f77cd867454c86c54998730571c6c9c23ddbdeafcad5f32636210de0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "468ae975d9c873f513f08770cd35f69a79ad4f79"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a120ca7510a52cba19910dabc08e3d56ce8f01c78ab76624e6daf9c42a3c0f69"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "996efb406d79ad945bd3a0bf6bde149577940674"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "6b060f23731de0f6c82d6e4e0b196ee3ece1b7ed5e728852bdb826713eac6534"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1936a08805514eb81410b970f5d7e19662627e6e"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "e315ee64475e692993603cced7c4c2486f5f7fbdd60706f1ed6d5fce412fb037"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3fbedc432032a595f2a8433b0db2c40389d62ac6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "6da63b7ee2e18165a06184f4063c22404dbea0bf8d9bf9f90828c469046b9ab2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fd1140092c00cc5dbcd119cbaece4b38da647bc5"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "83df8fcb353c6b73caeb83353a849dbbd0c793c84c8c532fbf63f52063003e1a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "505e615f04b5b500e971396072f6ee8663e1300d"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "4509318675bc443e5a518c98baa1b4ccb46992d9ca8b6af8c39971b509df05c5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "52e930032fd294ecfd0d1e9664161ce8575b10e5"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "4f3c7edfbeda0edda0b927f41bca3cd242cb2d7b57c15becf10c305316923304"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.20+0/OpenBLAS32.v0.3.20.x86_64-w64-mingw32-libgfortran5.tar.gz"
