[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "5c13a3ff89f542e7cdf89ce8ee22834bf69dba53"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "8b7e51f5b5f07b65b933330d14369e718a2890d6a215e2ed34c44eece5728f80"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "c7f908383a86290a180e4d2ab85957ac17da74df"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "446e9764c40e4d06f642ea498f770e9898b151ce4205735eeedacfe70a224678"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "2bc25ebe5f725bf979acdaf931733a2fd6b44ac0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2bdf32b67323578f5481f229373397f87513d38bc7f483b70fa4c7ab05107e50"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8158e81eb3e09d3defb17a847ff4b622a08dabfc"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "73f4f32d05c57cb5aa109835321951069d7048172eefb5aabdbdcda3a9563ce5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cf90f388d23385bcbcbd7d896ef028ecac505133"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e9a6999310a47433579053980288c8f40fc3d0d831b3f5dac23a10704976c670"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d58f9ae6f1ab7cbe28f624c090da37e6a14cd689"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3ff429e294868041567c37758dd63b8dfd70692799ae24181ad2105125e75863"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf90f388d23385bcbcbd7d896ef028ecac505133"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e9a6999310a47433579053980288c8f40fc3d0d831b3f5dac23a10704976c670"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d58f9ae6f1ab7cbe28f624c090da37e6a14cd689"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3ff429e294868041567c37758dd63b8dfd70692799ae24181ad2105125e75863"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "016e3743cc293ed19541febb0f226f4f926d1f28"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8a78e68bdb0eab4278b145ea55fe00698367c26959ae375eee5cd107246a3b1a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1637a7a9294dd079cf4f867159c2139e65e02dd4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4709cfc2cadd2eae2abc796202997c59322bcc25710dd88579b476136e9ac024"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "edc4739b858d54c256ebc35214848394a1fd6c52"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "470cd16c87edb4ff3b6a1098f77761d610eecfc35521cf9232d37a4ca6588dcb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "74fe96d75d47a1a2b4bd5ecc38a1cc991020c61a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "963cb065406ecf30c603e6cd6c4c4f30de8e5f25ebf558ba97b07db3a6fcd9f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "riscv64"
git-tree-sha1 = "dd0f82adda1cd6f50e060222e2c7835b417a8873"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e7dfd09acc79dbe80ab12bb9302e27d25c6016414e69a4d3294c9a712f540bc6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.riscv64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9be96d65e1f0230979f5cd822e93c2dfefba2109"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "cc33c0d07d3f913adbbdb995fff6c5d42ff0dd97dc483f5ed4544422bd0c7838"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ab917ed38551d64e82ad5b564678b3a62a911c7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "dcf0e83fa67c92199966a0b1d0814ab948522672b788e9399ba7fa5092a8b809"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3b0646d38c35b6ddb29f43e3d9d135d953848c69"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e341bee99c2b9c61b42bf92470e39c48014d4c925b09a567fa309c325e572c5d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "472f00e61df8f15a734b8d97e99b6775c42fbe18"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "49c3e6aacda8053243db4ae5803076ee92d076fb7a34485c25db9cb45e1f8ca7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "507810cb672f77f77af06d467bf309387b47f2de"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "9f3b1b29213d8f97f9b187686b8be890f7d4d51333a49d2b0a769249d906caa5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.30+0/OpenBLAS32.v0.3.30.x86_64-w64-mingw32-libgfortran5.tar.gz"
