[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "492210f7eb9e2f9992ebacb2adb6af1ef56492bb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e2786ab3c111e3cb33f4e4eda50de5ea536aea99edcc952e7d6a87c82b802c36"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "e4d27f35eb1d72bc7629ecfc8c2838f04682d2c7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ae3596cb668b02e7c82302c8e7b3e445260a32252b5d85fdc6bd7cddfc7783a0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "357a80be4be7e5599d633f1bd3a17a32dcd4fbdc"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c94e277724c5ef483775cceac9f16b778c8c4a9a823353dbd4bfaffd137d7a58"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "9248580b430bce63386cdba7187dff9f00d08018"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "772480f50a235b311a2d8e767339cca46665d0ee4aa39abf24f3ec4d4c261f5c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "ada30fa355e70abc17b2255676a20d67b8c891bf"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "03b70ad1cb44c8530c66fbab8adfd6d1ca0b7c66f34a6b4cfe8c93c264c5f881"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f034b454f3faca7eaa0c642a2bbf1d5440b453e8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "13861d28a1832ce0d5f1b8ecb84de2f19d7970ab9188d07da6da209ac4c4e5d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "c79ce8a6ae8314436c7e3e1e9a111b555ed7856f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e38be09ffa8a48010e395a8cf57d0e2348d8147a4724054962baf2750fabe6c9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "14ca9d02244264b7a0bbda4af6c808aa0b4effef"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "90bb169c6fc582243eabf6f2849d3fb53b0b7e17a3e39f4693c004a4f3249f4c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "6282185a74973076b77fe1eec2949cdafc0d75da"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "edd34511fe5876f47883eaec62bc2e7b220d9396c32c924e5496a6cbfb86a0ff"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "847721f3a09548c35caa90166bcd9742e6afa359"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a9dd680a5bcefad112d03993a35d6de434baafc055a71e2f4961d5f8177b983b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "12886dfbe0b5436477f6e7ae006384295e5ccfa4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "70c72d420d3358c885f00ab57b48acbd1af76b3d575fd77071e36fbbaa00892e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "07ecf55786a68ac74334920e9c17591b378ce770"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "417fe312177ed42a6a95cf4b5bfd39aa202199ca1e210d9a5bd25b622f511944"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "279a68204824659e67266901f5fa1ef2636dbee5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "668f70e1b4b76feee0ee9d51f2b256dfd2d9a05f3c7936d6ed5e3bb16c6f91f6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "25e634e157ebe11ff8b8d7dc2776d76b3da6c548"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "50db036850af08df7b241ab25f5e7f668fc0dbb7ac779b899693f386af21fac8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "609db00cf8f4ee2eff811de6de1547451db73dc7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9931954d062b0dd603c6b4bb049672404726bdbd4969b22068400accbbd233a4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c6f5315743f330a2ac770fb2f92681a744800b4e"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "b945a95923389da1ec7efd76bbfa1337ac525a37581053dc6aed0cf113c5a1d7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "5fdc224be0d83845d5da8a9c9081d3638587d74e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b79b8c5b473885c7e4988d1a62b52e90d9f5034c8000b39e1b831a10ba753a5c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "0c24193a281483b8f262e63c822f0ca78d1dccd0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "04c5b704ae04c209d7c0f9506c29bf870760272096a7f106b4161a803fbbfcf6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b6208a09245eee380df85497c09f4b18d1629220"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "41ce6b10e963824d2cbbbbf31e02ba5edc4784d9ce8adf4edfd611042753b472"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f79ff8fce5dcc35294d3a9e8b780659ad7f67fb3"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "0e7c2f8125cda30d1e6cae556caea06a7db3b98479119b361826f5973316632f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "922211de5c78b4b724755b15613484dfbdf0de44"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "eb21686bbc2e880c5c0fe59da595816b427a023422810c2866ed826626763fa7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ba5fb70b132c566093d2defd72e8734c229db4ca"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "99d88d0a7dc55bafe071c61a231fe36279f89317fef196954dbea80c566be96d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "046c6a47f361d4f05cc5d20c43894bf837fa4535"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "21949a80fde51fda975a423c893843c7b94557f9286bb73ba079792e33be3c8d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3e7121c94fd562aeefafdaba9864c80a7c2aaf99"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0bba4279e2e524a6504c16b7cc4266621ba09f62880b6847e291955c90ec5c6c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "2c0c6767c943eae4997e13d4f9adfb56a9a44b49"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1bd5dd9c01cb418d3c1b30b0d02826c7f193883e5a493b38728b81db52f318cb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "8892cd3b1cea1f00866ece791506c1d4f27a6078"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "376f594def5d788f2d235b02f6f54fe7e9956e893ff3a0a42e12abb0ac1cff15"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d5fdeee188694907bfc1802cef0dc321cd259f11"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "56ee6d750897c91f29d701ead5b2f44a2a12a72d5c1eb9b09dc2c0eb3b65d1d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e01b57d28723f17d09434bd41299a565bc37f714"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "9c877be5d99c2fb5d479e72c5945d076994b720431e11bfc1426ff69c9147183"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "0d2511cc940b4879728b7542cdbf306808d0755f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5046fbf88664004298b5033782365ec2481b012c08e501d81aa88f341b00d6d7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "08f25e6bde93a4c80a999b53689d723fad1eb058"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4ba05d858cde46d35120295e2b0f549d666327b25f15892520dda94af3ce29b9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d58068ff2e6d0bfe986f1c37b6a9fe0f38302bc9"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "433ec40a8496efce9680bc6297efa510374f7e9038ef0eaacd314fd7133fa278"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "30d69536eec1d7c9f77f45b111bafd8d11b1df6a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ee396e4681f2582bb1af846399946bc877771e7703b51ded58d943eddac5efc6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "badd732aff32c73579cff0e6bb9c89345d84c0b4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fa5ee765cea55afb5de007c4c9fe28db10c75f426a895f39f57363da3e248a71"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "bd19d27ba58d70b43210d567229da915cf6bcf28"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "639b8f40d0c8f9177574b413b9e475eb9045abe2e82078c5a4dde4efbfe39a07"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "70c990ce857893caf6b825052fecc19691aec9f9"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "7673c3c0eed1e48d0bb3771d73a9b192e95af78b134b68cb40cd69e533849a53"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "b585cca8f397efbd2256be0997b556c2e0ec1b4e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ad10a79218b8bc8ccdb442d640bc392d8c1d41a89d49de116819f022525d6cc5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f2678747db78e018e72bfb1b48d508137ca5b31d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cfcc99aa3a9124e54225e01299e86e8b7599b0de75835db12d88e643cd1ef83a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "67d807774f6cdaa560b2b459a70132d2a832c437"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "24d3be8016ca46467d8a207334609c761bc6b7d3a07634ca81ddd2be52625a1b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8779b94cf6114602331fbb4b3928a427e9a8610a"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "bb41f81ec7aae04a773c188fe9683bc6ad47af211e87f3ede1195ab83961f951"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+2/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran3.tar.gz"
