[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "f04f21fe549632853f43c494ae531f37379dbe50"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "887ad603d2786096768b8ab8413edc124adfc1c30cfec0741abecc63223bccda"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "54f0c6b30deba6f3be13dff2a1ac548b190be3b2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3b663787f6a53a90a095098bd829a8104264adaa66c8c78e7d824041d2bed528"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9ff56d5bcf4c1bc350af71e78daa11c686ed987d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0fd0c2c76132e9c55854cc67273bfc333f3b3904c9013738188caecc43b5643f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "98c632ca69cd52e41dd241cbc7c04e6e0339b2f4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "eb27765f1c1b0db91d4a0c8bb897acfb9574b1b79f522efaaa410caf793f842d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "dd357d343ee0cf9be4dae3206e61dc1198350e58"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5b553de049ac3f20c32e3a70eb006fa71145268684a93f2d9af6965c840a8889"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "f4c5be1eb3c91060173505dff3a9efa1002de914"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0df14bc532d4fc26bcfd422a994eef7602904a8b9f1bcea3b4d2d40f197f4632"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "91dc44397e0c2f1cbe097f8a932580abc0adf7f4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c9355b99aff20746b2603b78af1040185796a84eeade4da845ab76b64452172e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bf96a2c838214eaf44e3bd9de6fb6e3dc4dfa5e3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e638155ab543241c662eb7b4df5ad0c5ab5c8c31ea23737bcca1bd9b5a487dbe"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db01ea52060e37bdc7fa26e7c81ac02e6099ae6d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "317a15439f80e8fb68f80dfe45664c778cbfb7b475b0cd421188743d5bc6c756"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fa1dfac5361ad0a99cf3a80bea2354edb273aa56"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "abcad426a3d2c992ebe610e9048e7dbb0b191239f5bc4a5beec5f9144941404c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "704a52b7744409eb6d7566180b353e5c68ba8b90"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4efe1c939d4cca4e221589e4498542ca944329df74fd0437c566af1853e6e64b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "09e4ae65443643eebcfe00cdbc7e40f26857f95e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fc2d983f381c2d19bf39a63f55e211eac1e961dcef846e5d3e2fd9320ab19159"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d3e78b16f8caca296ee203a2806741a10dc9ebe4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "99432634f71214d51d866d7334dd5f60ae17ae52c768dc128b84cef53de2d54a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bf96a2c838214eaf44e3bd9de6fb6e3dc4dfa5e3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e638155ab543241c662eb7b4df5ad0c5ab5c8c31ea23737bcca1bd9b5a487dbe"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db01ea52060e37bdc7fa26e7c81ac02e6099ae6d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "317a15439f80e8fb68f80dfe45664c778cbfb7b475b0cd421188743d5bc6c756"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fa1dfac5361ad0a99cf3a80bea2354edb273aa56"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "abcad426a3d2c992ebe610e9048e7dbb0b191239f5bc4a5beec5f9144941404c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "704a52b7744409eb6d7566180b353e5c68ba8b90"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4efe1c939d4cca4e221589e4498542ca944329df74fd0437c566af1853e6e64b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "09e4ae65443643eebcfe00cdbc7e40f26857f95e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fc2d983f381c2d19bf39a63f55e211eac1e961dcef846e5d3e2fd9320ab19159"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d3e78b16f8caca296ee203a2806741a10dc9ebe4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "99432634f71214d51d866d7334dd5f60ae17ae52c768dc128b84cef53de2d54a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b71020a7892f7cb059641e1ce2410efe782e42db"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "855833584a395a73ad1c8c3229ff9f8e57d7edd29e0a5b37dcd3757e84422ac1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b2e2ebab2e82ec7f764e07d36632f2c491942640"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4e65469210c257a76394279eb9f9723cffb9eb73b8c51509e8c93114d33e1989"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "4bced8a6bb9b1a8715ca66546b8ab85ff530741c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5b3c4cc06470907930875f015907937262627aa1c0596144305fc60c18f75564"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "270cd83dd4e38dc07956952e167c09b6174f4329"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "08f4abf93794701a5cd4f991e7c3313cf7a77ab2c12003816af9a8a347705354"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "c49ebaaafe1ada72fa7bfdb6610afdb4f69570ec"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b843526a091b5f3bef31fe7f7eda2937956fef87b3e282d8c9db4f9efbfe63ee"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "7efa18cc0b66760ee1fa560302189fd27f5ff50d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "10243556c444af2520be801096ffb7834dc43e7921ed2d7646f9c4bfa7043295"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "afb41a0deb03fb1f8f3585e100d7ebf1bfbc1348"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "6a3fd274c2b9254c3989d745be3c41801204c68d6af9e41ed9f265bb25a80d07"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "6634e8330ad280ffa81c9d3d04fc3e798ac3809c"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "1c187a1951d391aa6543e6e7532fe1bb6e1f4ad7e0f949be59b8d65574dfba50"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "941530d1d8b96dfe1739fc8d36f41442b8a02c7f"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cafabdb5a09188aefc3493d1588f85993dfb332d27f1442238e47a4deac1709a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "4fccf7895a07d3d09cf2aacef290ac746b62936a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "99ca35114a52164e0e4605e188e68b91c3a995895cb8a95699f72cdca07939ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "452ff41514d8efb0916632f12e771e3e07d7e8d7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "14ff9174fe5d48e685ca2c5bdc894e3218b61cdc91798cc99eceb4ab566a4811"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "1b5f33fdddfa16795e8d243714e54048a15a5467"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46cbc21bc83b6732a6383a680da64aa5f30cede31af3b56774e168c20bc10f06"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fd36ef7f112530fa4e1d228ed375d4b60bf4369c"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "dafde5838de55f7e6b20184b2acf80c9d2e5d88da54e012d215f64fa9b04bbbb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c0e5612c0024e60a835996946d28f13fbc24b784"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "99bad84c869f994310066a9a1d8699bd54cdf089953a43dbf46c5ac66d98c037"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fb8a71f9fe2b27c3150a0a1b645908e992177d95"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "e60cea83fd3eeed139bce76215a84e14d95c0e1d8f709bf034b9f1a41c3860c5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5ab4333ff79a034942f95e74e65755543e7532f7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "33e15e72e20e7515b06b82db8d6c71dc8616823c29b1917e093f119443a2ca8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "604e718dea0e163db4a129dcb2ec371e552cfcbc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "dd82858f749ddc2570c956fb09c2e091b4f82c2d414d777922659ad381cb3f6c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "90ecb2c4535ad3580b99a14c353e7e8dab45d622"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9e85a0c054c3702888774aaf54026cd3a5c2bf30631625d752b94a04591c5786"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e296e8ab7c94c355c1ef38959137bbe3b592d4ad"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6baf160b3240f3d88386bfe1b4416b282b40ece932fd77fabdda5c6004ecf468"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "963c6c848957f21bd32d3d052b52e60e1da9dd8f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2d7aa946299ceac9ede97e9601deca028bb1b3a61086ad6bacbd1eedec8c1dcc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b970a2d835142a1f21911c4f4416902584854ccf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "47b83edf1f07002c167aef2ec0dbb2c960d664088074caaf8f6767da18f8bb8e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "204a07230a88d567f5f4ab3e688cec9347018358"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "f370d92b287c4b2d0f30468627770a7e38a5bdace07750548d9a7cdbadc919a9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e14b35937a024bde40e3c51d523bf7e0d0f89bc9"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "0cc2bd44ec7b2f4f19d495a18717405072fca4d650b0e8ebf32a58a6df27bc76"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "cca06f98ca6a074ded9a4512a8a8c7c07b1ca5be"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "f6cefa13bdc9778cf1dcc2df7df93a3a4ec0c36cfd493479b1d54591a229390d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9d47863f2538a12fe1acb585163de429c7ae587c"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3c3194de8639033fc8ba93ce793e6d6112db4d1822c7c3d7ae4bed5913c93aa5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "eeccefb494efacd0426c90f840c08f8f1f5cde27"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f10fae04a60dff91ba2814e7ded9c4fb0042956303afc76715ab38d58e3f94cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1c6cebabbca78e72a8563a8e97085c78907aa08c"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "c4b34de4ea633d11a83d4fc11e6516aad8ca27304a8e77835880f387c5ade078"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+1/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran5.tar.gz"
