[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "10b0bcd3b1f24be8290f5c66be77c4fd0c1897d3"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "25d77e4af4b3725f0f8115454f91e3972f67efb76c005025dd10da5928b91929"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "16b5bbd911ea4b1277dc7c6175eaa2dda6891fa8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "190f93447c42b71051b98e2dbd87d30fc5e4d941622f1a53b024fc6957cd2d38"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "cbf69d5adfcef43efefea2e77ef3e08b0786e436"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f5ab5f321e0f131a778574bce9488fab3af1a2e95edd1fe9ec04cb7e19445cd0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e6f87e59bbd15d692c1d988be7229f709d0bcb4f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a63be2dc9d094ac917f0005bf1cfd61a68cff9cb20660e116fe3c6ef0994c738"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "4c553b470445826568c9d70f3db88ba259d3f91f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c7d02c356aa216fa04ed48d707b13f55c1b29299d8a224017972a89e90cec91b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "c64f54d9fe0d71725a2796c0556caaa072e095de"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "49d60cf8a07d5d052be2eefaa500c33c24438dc97a5ba538b092898402b097cb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "3d10c49fb083922e4b5edbe88134d19ffa2c29fd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "401ca4c4eb476da1532ecfb9e058f5e41d2460fefe2dc135875007e5d2a67b9a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bdb362a01198f5bbba354fff2fdf3e3934619c2b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0a2bba4e1d812b3be1b89d68590342bc4a545152708e199d06eef9cab89377a6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f14fcae80e45de45685d2224f485eae1f7effbbf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "83c44401ac340ed0ac645befdabf58ec716799d8d7ccb542025453491f042519"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "88d990bf96ade2e2b12a8c7e75de71dde9a63ce3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b65a389c8ee967297996aadac8bc04afd49facd2375815f63b4c05c76caabea5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "43234acd2f75add141bfb73d823d7c8eb5ba56cb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b7be612e12afae6b5d3624aa03ffecc2dfdea5b39b89aa024d3a2ef97e181e95"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "64313ee24dc2d1aa0ebcf385b3edec183c1cc04c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7e342ff21ec5ad7260da6e69f5b56beb90282fc784b292bb20ab30114e0e944e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "24492bcc2fe795e4e028f0da3c471859d639d31f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "65fce4b47e7431f0fc6006b032b496a6d83afe60f38d5fdcb382be5183eb15d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bdb362a01198f5bbba354fff2fdf3e3934619c2b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0a2bba4e1d812b3be1b89d68590342bc4a545152708e199d06eef9cab89377a6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f14fcae80e45de45685d2224f485eae1f7effbbf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "83c44401ac340ed0ac645befdabf58ec716799d8d7ccb542025453491f042519"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "88d990bf96ade2e2b12a8c7e75de71dde9a63ce3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b65a389c8ee967297996aadac8bc04afd49facd2375815f63b4c05c76caabea5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43234acd2f75add141bfb73d823d7c8eb5ba56cb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b7be612e12afae6b5d3624aa03ffecc2dfdea5b39b89aa024d3a2ef97e181e95"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "64313ee24dc2d1aa0ebcf385b3edec183c1cc04c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7e342ff21ec5ad7260da6e69f5b56beb90282fc784b292bb20ab30114e0e944e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "24492bcc2fe795e4e028f0da3c471859d639d31f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "65fce4b47e7431f0fc6006b032b496a6d83afe60f38d5fdcb382be5183eb15d3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "8208d654fb042301bb5cffa10c4e0a09aac4800e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a434319af2c37acded47196edd87679aa29ccfe2f41034732acdcd0495ab41f1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "46260c66460a247165dfe95991c9da9fc4c75b66"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "dfe355906db080364e681daef5b8e8f4cf5b7b1095efe67dbb217fdde258ce5f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d21875b8290a666ffdab7c5de322b750b4e0854f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a3eb076fd5278f0ed0e77cacc20b4d4a27a94a4afd055c4ff04ba83eaedb159a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "fce927e9be9351e97f1a636dda307f042a0b19ab"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "840335af4a5bd240d50d63c1cbf57142432c4cb00a815b3c9a7105119c9b0ef6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "65cb675b5bf7d76ab8a5245c96cdb127bc19416b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bc7ccd87ea09d0ca6841993267e29adae093f4635550fe50bdeae573163aa378"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "5bb540eb5d0b2bbda7ec1e357b1e105bdf4504e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9feba7fbe805e819f8fd459acc7c0f853e61a10d40e178a17724a57cfc6eb35a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "7545acff26a42bf0cd7a47acf1fa39357463d4e6"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "4a7e516e11e6f8280c367bbbecca88be5a31e2265b3c817761e1e172ab341e9b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "530c02f082e38c4725e6d3a427854f4f2c96d3cd"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "354c6b9fb1abe246624f9372c7cc3ff68c67a01b6349c49134d8299cbdd55db5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "38b12bfd6e3fafdce591e578d9f8cd76f10c6ef9"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "8e4bc111491928f3654e7c23083426d78eb9158310587cd81442628c08c282d9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "92cf1d8efaec85ef292c026f10b1d6119c18f76f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "32fcf338effa159ed50a096854df2f761f684ed68f572e9800448be8ff60560a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "3a072f385cbb484d673ae90fe6f13f0e75dfe50a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b79742877169eb7a94569ed29fd6894ed0dff5008d9816654041a607673cc66c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "a816bd3333ad0f48bec89fea25fe0c159963bce9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bdd7ff2b8e14f457aa374ca17d796f27af5731043a54c50b6dccdeac8964b490"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9af6c5eb42eda05d8e06e5a2da4774bc30acf502"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "1f3902cc7853d0953d461fba8cb828106b5c69a04a452283cf485a4d41901ed6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "07751cf751fd28d449247795ab289e31fd7fdefc"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "ffbcec4418850187bdc94da855674c60742e14e2dd2d07efa5ea9346e853fa36"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "023157501199a753608d8f4adf38a1147a2ad00e"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "e152730f00bae2b562cd46a488476e06fd51ea4712b402ce274baa59fbc2cdd7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "83d0b02c2994064d14d4285b8097729c0cca5c1c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "106487eb778a0abd94d7a3e1eba7b63676b765ff47221b3886c9e5e68eabfab0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c1a0be92ab0626c286a2507b265763bde47eb3a4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b41f1dd71a113fecc29608e4d903927cc306c7248410c3ac35d45609d51d66f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "93ddb84060b49f38ec59d4b04a3109fedc4577d2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ee7ef524e5d9283c3e9b8204d9b90eeeff6b22a056d45d91608c472dfff11347"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c4577e537038e00b12e9f103094a3161078b4041"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f49219fd5e340a595a571dcb7590add65a80fd6eac840ceae7d540ce65410096"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5ebc086560f408b22f6928fe9ffe89f14012aba6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f7b0703b3d050bf3ca0eb1df662c7a4805838f72b6b85f7a71a3280f2b91b6a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e350d74937c2eef1b3388d4e0e9a0c3c6e8e54c1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "832b2e6ca5efb34815788659352d1bd7198a6dddf92690ebef1032021fca022e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "f4ba6dc0b7189a60310fc363ffecd63d1ab02e36"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "fd6b3faad366780d7e1fa176bf67d7c89409069a91d198a361f72325125d98e3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "19f5c4835c5a0a7962169ccee1f41aa85ff17dc5"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "6fa79544b6e247e42f0c9fbe02c1cecd3e2e39cee974b8ea301c1c7253370927"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ead29384bccdf40f30eed232032b9516b688c173"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "ce19e42149fb04dc4ae8755e2a03f7133ae27a6ff2db31a37b43ae37a78616af"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "dba95e90b217fd181059c8b22ee907bf605cb92b"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "5aaebad80d80477beaa8220c75364456e6baa442fa5f193ccf211703a618cabd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "82fdb13bd9a5d8a4eb8cf0c5161d4dba06fc6417"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "30e510a72bf678f9f57021f9775f34bd3244e46a36c4ca36e7f61b62277b6d40"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6e1f67132a48514b299f4b43bc0a8e8570fa760f"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "2c1a7eabcecab1260c4baf3febd2dd17f03c0d36550b5b534481462e15e0923f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.24+0/OpenBLAS32.v0.3.24.x86_64-w64-mingw32-libgfortran5.tar.gz"
