[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "45aa7e545480acbcf4a2344af21d8af2da5eb76e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "18638145c7bc75358d267a7bc7fd696079147f41a8f33f9bbbe84c7e2b2656ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "0b157e49f16e9e405984aa514cacc1c0f3f3aba1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1341b49696ce57bc6babe234e7cb6c9157909fdca26fdc375591ae0accf31003"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "9fdd51cb7eb63a603346c3bcad1e5af278ab5c48"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d3f0a9613b7cd9085e4c38dcfb987a860a663373badd07289737ad1acab93de0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "887e1d74b2c828640adfb5a612012edab6122543"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a2800f586524be1e910c2a347bd2c3920727b6a66f414511a78ee055c7275950"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "943d4836c03ad6ac02cee5b654311008683e2c25"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8274c226caece30cec99e35fea7f70bf8ab064b036f79fa568bcfadb8c0e2786"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2bed4fb00871d6991b18de01c12190ae5f82970b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4ed7fb0262748f01b62101568cf7cf1074d97b9a3737bc3a375f04f0c8688cf1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "6049e150125d4889775e3907dedcca569a6576d1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "61e8194f0553d3d0643c2c8c40fc0be98a898e884d03f58b2e0422b2bfd27fcf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e1c19adb0ed20c33c496a73073e2f17bb44b35a1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "5efed23502a4309b40dc4571d62f02a33811afce09e618aa672a2d98341363e0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "24e61f92ea23cf25a60a580f9950b6cea8d177ef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ad843ddec2106484c6336c1c164e6d08776cbf2d87337248e0f940c49a98d0fa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "884ee2d6947f629bf586ce33ebecdc67d32643ff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f8f8e2ff1a443d1e0c3ceb99829558fe31346e5ed4cd002a8fb91eb2f158abe8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "e7355a32d29d25b7bfa656332d0bdec142f20b84"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "86fe8ec38507d3cd06225077442e4655dd8ddbb387c6d7d5ab7bb97633f2d9fc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "801117df13860fc5b6dc4956b88ee6961ac909e8"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "094990860bb3e75c077dc8aa69e3de211265b8b36f81054ea6e15a29177ca27a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "63cc0482559440956bc5a3d428d7a4e0a788caf9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5e277c7a19dcf75212a053407b70990f3f5e05a159e2e2270f67e2f2462df674"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "bda50e882c5d731e0c214fe59015616805572ca0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "08c97d2e46d454cee09229684a678702b52ab800d7bbebee633823e9867662aa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "fbc9aac439f96dbb787d62b98b53a2b54f32686e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9a5e53e973d0f19eb8f5bebcfaea8694039ed41307af0ddd0a5421a8d3d38d07"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fd31782a5e7f78ead8074c2c2ff20ad3d69ac173"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "ed0c5dcb2b78c79b44c400359591d6001e16f0151d57e415bbacb86e44eb256b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "aa7a15cf0c94b79b0f52c807309256f759654478"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "125f2379b4f8685978f2b4298296fa2f6ecac2fa32702b96b33cc6ec1ad29521"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "2b02f68b3a51c403e961b256deec96b90ea3e506"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "741084e08d253e099bd687da713c4565a2a294ae3192f14cad3189f45f4426f5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "16751a0d19306359d5e78a700d10788619746792"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "950b60acd3ef468dc00f6eb3beff7c6b180425c663dd8e239244195dd026f373"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "feef2ca672d60419b4bc74df658c898bf5f0c5bb"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "c5de0b74fd8d846693b7018fe5fe76f3c0a5eed0f4b4f5862e9e2ff178cfc523"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f27ef352a08ac8be2aeebebe8df5ccc3651d17a1"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "74039b76d2c4e9db97902cd3521eb017326c77a1481575cf8f0e60572081693e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "403a1c701edb382d4f64d1f3582620da57edf8dc"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "74740221eb30c0fd116fd0b7e58de5aeb48e788d56b076c626d009fe80a45489"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c439251c602f411b615ebb171f341cbc9428e45a"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "127549eabe4f7c9a50ea3c42ba3ddfa9b144384c105e7c63c10159e661827c59"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "fc29d04b579697a57b41a56818759410d8d132e7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5ff9808706feb0099d2b44fe73ee07c9e1fa6168a7187bb3da8efd480554b05d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "70f3089a7116262ecc3c38b9ce7aa5363182fd34"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c136cf09f883071be1f3c8fa4f8a5ccc583c363d41739e8d94d6f655401c9505"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "d62e52656f4afe44e62f07aba7cd7977d11831a2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8d82d925026a0dfbb9c85a2402628797d95feb9b5b9dba5b5c11799a60716495"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "442d3fd4137efc81bea92dc06fad8cb2fce8eb7f"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "81eeecca429402928672b7802321f11b8e15a5adce7d76336272fd285bf5cfb5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d591e7ca1846f69c7fcef00c424d35f5305dab65"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "45eb987c901e23107c5dc933325849724ad2615f3ca15a18e56f5b0fbec794ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "2f8b9f4d2a20dbb8097cd211b40c59116f3a45ef"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2165d7070eb305fd9f9f198b97c09a8cffaa0944da5a76031ceb86dea3daa5e7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "e133e4f48e82c708f757c2f57ba5cb78e88d17a7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f8e8028e945504279a6537bc92c4f085a763de7ecdda63e9344e120460bec04f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "31a59e925ceee35568dc79b9d45d96cb6b310b01"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "eabe1bdaa907ef1ec807fdf6a23f4ae0f71fa0205772924ed41048575bffe913"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "a23b216ad99adb2a65eda5ec15f15a4c32794718"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9139f67d95b9bdc58c71d62e0bb383b00d565ed69dcade1a408303b45408423e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "9795b7fd0d08e1c0e952243ec4a2c80475f395a5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3cadf18bcbedc960221b46db3da8beb01133997ff7a59c65c1b9a0802cdabf02"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0e5e064154b9448689f2c9232ded6ce3ee0de004"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3ccb6d9f3a666ce07f5612494d8ceccb9454a3c613ba8594ec72947e37530637"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "7816894e390bb9147738db6f5a62d9b495562325"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "be1c4eee053b8c55c7d8704f6ccfcb6ab4776cf1b93ab02f44059d72c0427528"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "247962b5f0fb08bcbd1696b0eca9f023d707eb1c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0ffff879c432b3cc5a415a58c1444da30a854dab716028a650c4b81d5254ccea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ec07d14e14bfcd21d592100cd54360b78643c3cb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "486721b313509c39ba7685d7ba5cb647d36ff162c84cd581006a0f9ef94530f4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "52afc83c9a9ca6a1be9fa40844f49dc31540afdc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5d450a18c7e8ae0757177f29ff78af4e29f3d128e7e7d3491ab4e05bf7594ab0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1b86797b64263ee71d363e13f0780be6135b3b4f"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "330661f19993643159f09d153c6e34025745bfe70d64acb15a99c8cf93d6a210"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+1/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran3.tar.gz"
