[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "3f0043ec0bd5232803c3a43f989fdd944526d639"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "74277ccbebd8033bb5b0dfedd35688f6c3bf81330169dadb0d3a93e65218e9d2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "4967b4f6e63ac4d0c20d7b3335abd67d8b32774d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "2023a97d0cd94b8f1a27b218ff583af74cc4adb5ac51a4a95a1fcb241154239d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "ed4a135d13d34db8d75927ba830c061d2fe285e2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "81a9c8c5ddcec299615eed71c7443779e009a80bcee70faf991169e4b26cd61a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "9bdddcabf37dfabf7d2a01de6a794f2a69afb8b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "089ccfd3f3ac12804aa0f3aecfbd5cd3572dcb1bbbca1db241f0c1b88db6a449"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "6287f2109ccc20f78b1ec8336c03220d3f252159"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d9be72badd4181dbc6f57cdc879bf5481d744881343d0ae18213967473829b47"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "523e8fd4ec565409a77fe27bccf3adc3ed7d72a5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ef55ec261a6262250ff0ffc643b3b39ceaaa91489ef75aec3fd90654b981077b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "7ac709fdc8d1a73b4046efcaeb31f2b9de8ef2f6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0f92a59edad5330e6a8c644dc13d1612ccc3d26706cfc4932a0d1a09d34453b6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39fae0fe9b1edbc8cccab3935bb7cac4e91a2f49"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c70163270fb1fb1970a930ff1732c0a3e53336027853bb655a6933b605715996"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "dfd17ed4817a456301e305f87c33c48972ec746d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5aa1fb626b8feca1b677c30aeb97c8990918f8745763f67be37c1d14290a24d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c89004c9d0b8394935e1f37a11279175698ca8c6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "1f540a56eb1fe2226a4907b7ff467a0afb207245e355f37b68bf8564cfe7c497"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d19c2c92b6a4911b8ea31796b681470f4a2b091b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "92fe1f44156fd897bdc6537f4056dbee758d4522e0ce2f955af565b9f059a35f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b19b41ffbf1fe2849081dc2cb4a537b40e4d89f1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "80f04320f856fed8b5b5dc9f6e1a364e6576929c1fb34f25691fe9accfe8f1a8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fb59f7b4a4a5269f3bc8c58f6f83bbd2004cb21d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "b6b381df5ed72e29cb500fe2ca409ed17d7ca1f683e63a4aa86884fdd85c6e18"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "60c3994138843e8a3caeff7f7a39315f28514ad2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6301ed9c8cd0e8cb3824409398df160f3c329b8e6bbeea7921979a0272f780d6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36b1939badc7965264fdca16a855643fc26c397d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "553d19547db4384eb26477c54f3f59c5adb0d84cb85e4466d6baab44ba64039f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d2a8ff4d16cfb7d3fa7787e74cf77519e595128"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "17401cab1c3701e7b5ed84dc1504d79ff1957fec363f87580372845e126e02e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9f0e7c66cde8c2f106cab0f3f757e5da2aa85b86"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "51286c5424d08a8a27c13f5d46b35a88ba6d901d8873bc4220ff8e4f4987cfec"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2692f64b37f381ee93b21c35605606efb5d446b8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "88bf48d9db090ea1372910fa69628476f5dd7d6b9479e661c608d050a47ea5e7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a657c0edcc235b5b63299fa6a1e1f6f6d1b07d62"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "590bc6810333b60e20166d976df791325df37e44c2391d661a749361841b81b3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "407cb338ab7e67195e3b53270a8f66aa13d605e0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d1b195f1698fc91c7e5d780394b8c2c9d675a1ded6e897afd498bab604fd4dc8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "8a2126e5b88a0833f084c379693e0a3745f0c7fb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f606362236df927829e1b9d5155065d37230949c4e29d0b0ea841f8bbdf2c440"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "c619c4ff8c0abc54c5b491c599df807d445c140f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "99e0caba62a2055075fc032822c0ad33c1c2c7692371dae76525ca988c384c5f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "7df9412a97b080d087b38d383ce773e38a0b34b7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fa6fe79fc8fafcda2a90aef93692386b5cb9731fea68555e2446250c69bc7957"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3bd44aae55947ac02e3db919915f83456c20a5f8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7b187fb1f78ebaf8b7ed6c19e6afd7e62e0bd12881fbcdc970f966e466d5cac8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "b0c25f651d773590df7886b8285698063f5d3857"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c527ecf0b425468d8b807ef24d2ce8b1119e1faeae39a9b269ddbf35cedc21c6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "9954769cb7d197ffe518e8409abeedd47b8d5a4e"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "774217b914ca223cecdd7de0077fe564edcabfa46e3bae5d6a687a3cb049c8d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "361a20c57e28051e43a892bd61ce274ffc8db922"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "e58e3fe60c88caab0100527eb3b02d22645a3fc1cf4ddc3bf4ac1f3900f89334"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "3c8ee75afb56ee2897c3a402506d536b27e7e8c6"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "5666d6a790ab3db6e6be7618279a216b64ac8e2062831abb796c42e7f768bcc5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "0d371d26e0bc638e734a9d050347539b846e43b2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "25c792c92f94f30856b653a1b00bd61d605e729c523f5f3296a560c751e65f83"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "03fc81d514213ef1edc1273593c68e1f12cd95ad"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9f938ecc8c242f09c83b61fd4d0c6cd23d11b66badd114d90784431bfd14ff7d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "6b9f06378999b6e7eebc886b579398d3bbade3c3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4e6e920d6b868989db3f58ef5565da1eb1d71548ebd639193ae3e0c873dd4246"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2a075c6291b805a993020db8ec86b6d21663e3cc"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "6c76e522220be37c0a6d94aadcebb32e9c1bb29e92a830c7190a7647a2cffb92"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a50db255234a53689073a59c5df1dd1ebaa6fe06"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "c57b227f993aaf3fc7da94cc7f96e07b27b04a83ddcde5a124675ad1ed489d7b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ded5084fbede2cfd4e535b2ce91a38c1b1d89ad4"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "d0290b44d1ba7c307cce6dcb986509a5570b80e17a30f1f0588bdae41e7e757f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "4d5f144d40ddaa85a7f76e656e6fcc9dcdc9926b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ca52eebe40a6d4ae63925bd61513257a0f4f62c02dc4a7552b25e4612f4a7995"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8592db287c005f7f2400f007942d937793d793cd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7fb3abb7d40a3106269157071c88d7bc02706d72824d694d4d0f3fccebb0a5a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "60f8ce376bb35e31e72e795f535250000dff81d0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "602516e4a2d589365b2adcdec7999070508b8cfb9651d9e100cc4518b2f9d3d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "8a811c2b643ebec967ff30fd463a36fc6327a2e6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "bb64dafd411446ce39998eae3f7d56072e34a950fd3b8d9ebb26ab993bc04da8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "e1b2e7af88c122eb8f2b1319fab95ab72adf9994"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8a1a1087146286b27c11c3f64700717b85529ba03b999c5e96f55ceb13866468"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "83202fa90b020e3f011717546e4a43c2fc5c7232"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f99aebe1ecbd6fb4303b0580ee3495fd76f8ff3fddff806a7d94290fadce0b05"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "6026360f3c26bf3a5bfa268d223c70ebce793e81"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "7f2ee8d49c41b6bfd906e08d53db872138857c76689d9caf828826f99b0724c3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1f10cc6010171db1162a3aac808fab8dd3a1be5a"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "20ce5b866697033bceb5eb1f9b7d4900b2b8adf90c1ff416e175164b06962c84"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c6b8977a3a102bb205a800a412e55cae89d0b33d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "d656bd8045aeae6bf265ba7ed720294af8a736b691c4333726453e5ad55d5849"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "17dfd5869d063f348e281eba8e145a6347b777db"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f2eb3a5ed7a6ff7375801b3fcec7a46b2e93d4f4e2fc9e1e49aa5b6b7453b9b0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "135b9800d4c7fbace8737255db432667b14dc421"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "b8d2b774eedc155bf7716e6d49de3a329841eb55120f623cf765b3660c5946cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5de1a50adaf532995ba4a401b589d089de83aa1e"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "ffe948d9f24fbda027ffdfe790ff07d9d3e9ddb824617082cdb47e086e9e15df"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.13+2/OpenBLAS32.v0.3.13.x86_64-w64-mingw32-libgfortran5.tar.gz"
