[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "128733d8f7d868168692237c63987f8b41459920"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "9520a3c66e7ffa8abfe28c78df45bfde5c7e3582f68a3f3fc94ffea02e06ac86"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "7716af784beb45862815b6bc56f7d33ebb203432"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "58382493b67a76d0f6bd59a3f218cf2b756ded9d4646675cfdafccac6768e9ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "91490f95534891edad894dff98580ddd40a47b2e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ce418aaac416c91a066eb434729e3109859dbd7e4b307f2d0633e635b030d159"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "69aee25f590ef7bba7541e7a75c8da073bc26067"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3118a50181ac6ee04fef6eb5596a66bc5b10ac47cf9e8bd992d0e527db84fd69"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "91c5b1a86cab0679eefd20a4e5afdca7c96e399b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "de24ef50a6d12e49a23cd74cd35d88c7db267c9478a450e52361ff2bac9e3b1e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "21801acfc20da731dbf8acc23cf8dbad81c186e9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d7b9ac332a6d993a0b09156f40dc980512b73ababb4a8e0765195cf140effeaf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "4d149796367b9feb412da69ba0c3484350a00c93"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "9ec7c0744516aa9b52dc86b4a2fddfbf3be572bf4016372ca94b16562eaf59ff"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e51428a5b03e31642cd84107ffda04530cb7ccb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4890f0431fcaf751c1f95c249eaa9fb7006fe159837d1fbb98556ae615843bf3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "02bdc8ee36872b0d8a3ff1c816496d86bd8ca1da"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ccd9fae0b0711eb26c6f738aea0fc6d183a770027ed3f56a17031358799c166d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "53e3c3a4fa30a1273ba29cd65265c3164a231ef2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e2b059176c7cbcd094e40ff7ff2558a5a29523ca5de8935c7c3dfedbee41a1d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ced546d5a453ad275705f6210dd4948f7a85d17"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "62d02613d7c9e56f263394d50192d7e96f943563f2f01b39702e97018500d5e3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f9b5d47f17bd083766860a1f2fad1024cc0a57d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8819324a21dcae225e6d43857d7a9f8824080a82fad9f9f5a2234130fac39d68"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b5d624ca1594451bcbabba9c37b7320ccfab71ad"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a78e79ae9baf2e390a2798b0f5d049bf79b2517dc066e5f544b7a12a6de0c9c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e51428a5b03e31642cd84107ffda04530cb7ccb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4890f0431fcaf751c1f95c249eaa9fb7006fe159837d1fbb98556ae615843bf3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "02bdc8ee36872b0d8a3ff1c816496d86bd8ca1da"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ccd9fae0b0711eb26c6f738aea0fc6d183a770027ed3f56a17031358799c166d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "53e3c3a4fa30a1273ba29cd65265c3164a231ef2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e2b059176c7cbcd094e40ff7ff2558a5a29523ca5de8935c7c3dfedbee41a1d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ced546d5a453ad275705f6210dd4948f7a85d17"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "62d02613d7c9e56f263394d50192d7e96f943563f2f01b39702e97018500d5e3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5f9b5d47f17bd083766860a1f2fad1024cc0a57d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8819324a21dcae225e6d43857d7a9f8824080a82fad9f9f5a2234130fac39d68"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b5d624ca1594451bcbabba9c37b7320ccfab71ad"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a78e79ae9baf2e390a2798b0f5d049bf79b2517dc066e5f544b7a12a6de0c9c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "e20f7baabe7005874207c25d077e0acdc3c0059d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "d38b19312cac73f2261d908b0ace404c4fabba0cdf03d3d8779c8ab0739f3dd6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "1b05676f3f78ef4fb427f3a7aa1504f30fdc4790"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fae6660fceed4503e156de1766c456d6c1e4a1baa560f396572f58c2469d7e42"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "45b1d9666d3e5312df9d16e8aab408cc962c73af"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "aa0142ec76cb12371bca9073419aa758bd43745788df7e8394552e92d34dba2f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "a66d5ee10caf21617e3679fd89da0df765fcca48"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "80920f04bdbab33017549c641252e9a13f64f5fe81a271fa885b0591101261f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "5d528d5e839a292b1528369bc0cf92126fa26e95"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0eb9b25cfc801eeeb81d839368caf26ef8926e0c5036b2eb3899d3853b59f4c0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "c30558a6b62b792311e94f865043240926c47e1a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "45887fa9105150677e55d97af9d250b27acc2ddb1a0b687f11fb2df29d4a66f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "84cc4846f9c80ade991242cf41d1542076c9b6dd"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "84ebb847103329938703995ba7022dbe0f2324545c419942209c2f465fe3d849"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "ed7506735ebe5af7a96a71d8b3ae6f33656ec2dc"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "43e929fcd58182f12917b877122e1da501f4993321fa5f52b3084d0425c88b46"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "941530d1d8b96dfe1739fc8d36f41442b8a02c7f"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cafabdb5a09188aefc3493d1588f85993dfb332d27f1442238e47a4deac1709a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "4fccf7895a07d3d09cf2aacef290ac746b62936a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "99ca35114a52164e0e4605e188e68b91c3a995895cb8a95699f72cdca07939ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "452ff41514d8efb0916632f12e771e3e07d7e8d7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "14ff9174fe5d48e685ca2c5bdc894e3218b61cdc91798cc99eceb4ab566a4811"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "1b5f33fdddfa16795e8d243714e54048a15a5467"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "46cbc21bc83b6732a6383a680da64aa5f30cede31af3b56774e168c20bc10f06"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "d9d66410b09b69be91024d109edc19a92391309a"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "c53852edd88f71a91ce0f93c104fa4e59cb347c3f74509cba17cbb04f4785cc9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7ec5ab0b454a5437e0e51d9716dec3998f11f197"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "c06af4d0761ab9031eb4c3682bd0c7ea39390339dfe67291dfce209d9a94f853"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "919e35ec8355160cc4b3a0cf973d91f0f05bd0dd"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "4f7077e24fd611bab27a82b4d56af2bcb64afc7455d2c45726a4c1523a072135"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "23a0012c1eb08c7b6e9e8bd609ce7cb432e4936b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3190e3e63afe46b4b0b936f527bcde2ed2153eeceeb28ba7d573d24fb3f9cba2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b5735f786bda0a159b5bb22c95b23871791edb79"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "fcac3ff6dffee4eca5b8daf29f278bc579fdce68f9e4c4a0ce91b886d7d11b84"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "b63efa5ab24c4b6c565a387c91899e93d685680e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "a9d5ad97ab2854bdc1a44c505327848f1e30f5f25b47a3ac733f38f446d71910"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "5ba3ff51fdb29f14ecff6ac61becae6f6c748eb8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f54248f52d03a535010dedf0afd2dd86e0f4f72830202d3daac718eab82f23c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "760b1be6e4a0b09b0aa1c8ed3495f453955aaed4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0867f7dbac0b4e8cab0de18a0a4508b8b4edc779abc7126cb90690107077108d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "111611c695ea83a860448bc83a9f6f17c6241e68"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "ba90414aae2009d776c947dc48afba373ed24570c759ebfc8d0861afae5c2cff"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "76f2628bd3e9bc2d59955ac9153817c6a5a8b38c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "2a9b1ca42884c62b45e0b6a5b0c880e67f78bf7a2a9b67ee25e36ac89a327b42"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "0b0a87067275ce292016c6dbb22e9272a1aa6dfa"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "ded6677936723691b1d43ff6f03290b0b1d35916a50d737ce18882943e126b0e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "342feff9113d6c9bdd5464f046c9c8d09b59e55e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "e554c3cc6220d22b42c2f539f7f467cc1d4abf4deecef7795f0e851ce3b3a1cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "9d47863f2538a12fe1acb585163de429c7ae587c"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "3c3194de8639033fc8ba93ce793e6d6112db4d1822c7c3d7ae4bed5913c93aa5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "eeccefb494efacd0426c90f840c08f8f1f5cde27"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "f10fae04a60dff91ba2814e7ded9c4fb0042956303afc76715ab38d58e3f94cc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "1c6cebabbca78e72a8563a8e97085c78907aa08c"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "c4b34de4ea633d11a83d4fc11e6516aad8ca27304a8e77835880f387c5ade078"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.28+2/OpenBLAS32.v0.3.28.x86_64-w64-mingw32-libgfortran5.tar.gz"
