[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "71d7b21376734c5c7fc9df393548c265eaf1388b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "070118dd23ec6be9eecdabf2370a883daec896df718c8b91ea468188944742ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "1eddd88dafc0f2e7ce79cb6f75b6d9de6fa1522e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "7b2215bdc4dc066d8a581c947b6dae963757e24618128bcd129db5a05a763133"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "9bf12b7b52bfcbbb91cb3309e2f04172a51fd04d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "05c2b5d25156563a6412b94a088f67dbd1575c60ed31eae5a13d3cfdd28e31fb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "powerpc64le"
git-tree-sha1 = "39c1e266fd9bee8982fb8234ad6adbe7394bf9d2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "72b9fb29a196293a1a392d69540380041fd21cf6730a36fac15f7c7537f8b3aa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "54a4d2a96f8827c24cb5028634e0e437d10fbf00"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "5da4f0bac3b95ea9bbe9cd329a1cfbd0ec33952991d2b9e287259ddc7d06af48"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "c481b54770c6e9a9175f0316a2845cacec44085d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "837c0f92dace355fab4879f763a44955bf080a5012590d22b512d791a15838c7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "f232635c23f563b148224ddd4d550089a0bf3a2c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "88c335846787791834fe4878752593c01ed1c7b1007b10cbf9ef3f043be34abb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "a0988683a8aed11f9a4b51a38f66614128e86d4c"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "b889d62279de09c4a91e41159926502ca15ba16af90611f4207db49b6e6bea1c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "a96d7fb41d074d880e45c41b1a6c64e2881713d7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4530384185bdb7fd9829680607ae17ba2977a4852a480a65050ef2e979d59085"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ddd99aea219650f6b7d292c19566934d5e0c8c94"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6fa3357071a013b53cf560457cb60e045ee3938910453ec31f4a64c674a31625"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "b30339948aed3bcdfad0afa483a74fc63156a9f8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "af45f521ebce58f9de9de03cf94265d67fd000d8ae53c1cc6cd5eb7bcd4e394a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "3988bed73211f0ed032b6ac16c162cf3c68f76b9"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "799d3ad6e7d659cfc5f06eb4c3ba44a33749499b9440b13b60b2d05ba527d427"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "21ce06d3296d4e4715f8fee81f9c89d2382b0bd1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cb703306f053e36613c080f47a49d8f5474d4c7ac02edb235e73e23b22231c16"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "465bbb9dd98c08d03f462679dd7d78df26f9d19d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "afb242f21442af1b30eabfb7d30aa8cd7133d2143db21ce149c7b041836fbf81"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "15212e544b86da8a6ab15097c22704e446ed284b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "130cd052a3d5990a2af486ab2d13f46528e39baeb4ff3dec2aa77b1ef9dce762"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "429d047730cab38bae3fc9737e7e309f92a4589b"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "cc4e1122809b14238c547e37b7d9576fad099a702028286f28fafa5523cb70f5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "c0cb8f4a17eed64164e7a745513061ee8965bc1a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c53cf34b7fd759c98e7aabad0179d5cd55813ec1b2441dc9c8ada68da3226f5e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "22bd3d5104954f62d79339f3a9990b7674a08688"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "cf8d44d3ada914484d3e9eff608bde7e25acd0c485535376114b5fcf1e609efe"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "d944a951c22675574541441b55d8efffdfe5c356"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "8d87deeb280009637e524bb47d6d2d16d30abdabab4371e10c9d2829525023fc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "2f3223d12287987c3135ba8af8dfa9cbabea0b2f"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "3cdae62513f90c4ba7c7e773fb83e013089b9d557db2a18d33faed47d2772cfc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "fd6563b0000ce018c95f69a9b967a530e220a918"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "905d9d0a7f2fee65f65983463301307b36a99fd9c645f176ca117a6d5c5a83bb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "345f4a225e5664798613c08b2a9daafeb05dd119"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "5b927b23310326b0a1e097d9d07efe54f3c2a86447f3b8aaa26bd20874f01cd4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "ce0fb8d42b75f7000f12974c7f3d8d79a8f18f2f"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "443364c5377f9c0ed5671162d6c27b5143c6cc01dc2046e5f53871a7a0cbe2a5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "72c81bb2b97d8a0eb06eb8c7d6d2ffabb9e8256c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4de8b1946e5916e773162b00c0304d0c395c15086fccf7dc45413506e4bd7733"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "4bb057405d777fcdbb2113ad5e16ff60e03dad89"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "3e32fbdfa7486b3feb20e27da6cd025905273ef3046063e8d360fb52d774a467"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "c6d4b62ac5f8504907fbbdcd5d764c32b5a435f1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f4fe9c7e4ce48f718debbcdd8de1ae8f00320f82cfffe29777403ee9ed55d3db"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "22b33b409ca69925f8d0484af3388863657de5c8"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "459b1f62cd4258335449f674d5a0df6b2b2fcfbe794b6d143ea8d8748ade6a7e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "499fbe2eec284fff3af430c500ed2dbfb1b278ce"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLAS32.download]]
    sha256 = "6ea233c045ab4aaebab9836d9ddbb9c1e7ddc12145d67b9d182faf8ac0eb2f51"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "6d602cd5599f52d3a88f0155e6b5b72246bd2c51"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "555eda86c436e345c243164b40fcd7aeeff3b8ed1800682ab27a47c9c7cbaf7c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "631c48d1da544bf464abbd05d134be19a8663501"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "0a924047d6f3055371a2e8ba828bc9a2ab9214664fcb6df8d4bee92545582c45"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "66873afb25b4605965abeb9b2b11135fb5fb67b9"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "c82d432edf29672fc936daaccf3bbc0e01b45317ba0b54b8aae8e596e7425551"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "aarch64"
git-tree-sha1 = "75705b144378e60f4b27f65062c8427807fcf372"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "c5e14c00f78cd305219c651e47aa10f3f7ea2063e175c1a0deabdd08ad3dd09d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "bbb535596a4c92bf78ac90bd14bbe82cb146eac8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "4ea067b987a901cf5a26ce1a14a013fa024508ba4f11bfe8b340b9b522a41541"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "711e241a42e34c0aa8a9998a6d102464a6f72479"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "f0a8f3b6b9b6953d43fa856540434ec2b77e54d7e975636f774023478ee4b4e3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "i686"
git-tree-sha1 = "4d2516e81a6d6de705a548ad8a80457d9e641a52"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLAS32.download]]
    sha256 = "d638acdfdc40638a826dfec73bebbba8305df13c95457528d0953e4e0254d8f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "1592e1b6970e857a36bd7ef4f954ce3038af0412"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "6b4f610937e3c0e64c368f6a8ae99fbb665cf3693aea8d138aa7c96a2b25003b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "7afba98438db003889d9e921bb153404d64b71cb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "e979f94c85387749cc6381a274fde5acaf86103f550d6d042e49b51868f83170"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLAS32]]
arch = "armv7l"
git-tree-sha1 = "c1e48ad52696ec8140b5d0ed6b07e40eb82fcca9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS32.download]]
    sha256 = "16ecd0d268f681a022db42e578cd20e038ac2242954d33ff35b66c0ea593eb0f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS32]]
arch = "x86_64"
git-tree-sha1 = "48a3409d4bc27d59b5fd6774327af03f435f3db1"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLAS32.download]]
    sha256 = "218f76172c74e17ce2db785ac8d5415263e707893371cb37a9651c2e8c31f91f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS32_jll.jl/releases/download/OpenBLAS32-v0.3.9+3/OpenBLAS32.v0.3.9.x86_64-apple-darwin14-libgfortran3.tar.gz"
